### ISSUE TITLE
Add spinner to "Use Case 2 - Process files" Jupyter Notebook

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#100]
In order to follow on process and that smth is going on, add spinner or any kind of ntification, after pressing RUN on Jupyter Notebook.

**Comment by GINAGC** [comment]
@samarthdd can you take this one please?

**Comment by samarthdd** [comment]
@GINAGC this is replaced by progress bar at the moment
