### ISSUE TITLE
Volume/Performance testing

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#104]
We need to start having some volume testing and understanding the results.
- Number of files
- Volume 
- Number of errors

Please do an initial validation with current implementation, to get the current baseline that we have now.

**Comment by MaNe2020** [comment]
@dpatel7 do we have some large data-set somewhere to use it for this? Can you share it.

**Comment by GINAGC** [comment]
this is duplicated with performance assigned to Farid,
