### ISSUE TITLE
CI for Installer/Monitor(Glasswall Desktop) VM

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#105]
Install cloud-init, python, curl, guestinfo

Install OVF Tools

Install Terraform Latest version

Install sshfs

Install Postman
- Import Postman Collecton to VM

Install Glasswall Desktop  on Desktop/Glasswall Desktop App

Step 1: Download Glasswall Desktop App from https://github.com/k8-proxy/glasswall-desktop/releases/download/v1.0.5/glasswall-desktop-1.0.5.AppImage

Step 2: Make the downloaded package as an executable by running below command.

chmod a+x glasswall-desktop-1.0.5.AppImage

Step 3: Run below command to launch the desktop application

./glasswall-desktop-1.0.5.AppImage

Configure Hosts files

192.168.30.112 gw-sdk.local
192.168.30.16 jupyter.local minio.local elastic-search.local workflow-api.local

Create Bookmark if possible

Clone Data-set repo on desktop

Clone CDR report to VM and only keep terraform folder and remove rest

**Comment by dpatel7** [comment]
@pranaysahith I have updated description
