### ISSUE TITLE
Dashboards in kibana and Jupyter notebook

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#113]
Define which dashboards can be useful for customer and start creating them in kibana:

- scenario (so that we can group them together)
- events (with time stamps)
- execution run id (so that we can track it to a particular execution plan)
- timings with start, rebuild process, stop ( we might be able to get these from the events mentioned above)

**Comment by dpatel7** [comment]
@MaNe2020 It will be useful to add documentation about how to import dashboard template

**Comment by GINAGC** [comment]
@MaNe2020 please review this one as the next priority, since the data available has been improved. For example, we now have: reports, XML, json files, file duration, extensions, etc.
