### ISSUE TITLE
Offline GW SDK and CDR communication is not working

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#132]
Seems that without running `setup.sh` from CDR Plugin VM, just setting GW SDK IP in Jupyter does not make it sufficient for offline CDR Plugin and offline GW SDK VMs to communicate

**Comment by GINAGC** [comment]
@dpatel7, @pranaysahith please take a look to this issue. It looks like the setup.sh is needed and it was removed.
