### ISSUE TITLE
Capture CDR plugin workflow as part of the development guidance

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#137]
- write an article about this, so that we capture this workflow as part of the development guidance)
- Include best practices on development and testing
- Folder/repo structure

**Comment by GINAGC** [comment]
**Development workflow:**

- See https://glasswall-solutions.slack.com/archives/C01SHLVNPRC/p1618654879249400 

when having an error (like pic1 ) the best way to figure out the root cause it to write set of tests that follow replicate the bug, starting at the first entry point (in this case the Loops().LoopHashDirectories() method:
Loops.LoopHashDirectories (pic 2)
LoopHashDirectoriesAsync (pic 3)
LoopHashDirectoriesInternal (pic 4)
with that last test I'm now testing the function that has the code that throws the error (pic 5)
Then I can debug that method (using that last unit test) to understand where the issue is (pic 6)
Finally I was able to create the smallest possible code that replicates the bug (pic 7) which I can confirm with an assert (pic 8 )
This means that I now have a test of tests (pic 9) that accurately replicate the error (this also shows why we shouldn't let exceptions like this propagate up, since there is no reason the main loop processes should crash because something happened with one of the files (i.e. the loop crashing will be a fatal error, with any probs triggered with any processed files should be handled by error logs and file processing reports)
In terms of the root cause of the problem it looks like what is happening in this case, is that my version of the hash.json file is not in the correct format (pic 10). That has been caused by a change of schema (the 'file_list' is how we used to capture the data, which is not indexed by hash) .

actually I can zoom in a bit more and write a test for get_json_list (pic 1) , which when executed shows the problem (pic 2)
now that I have a test that really replicates the issue (pic 3) I can look at ways to fix it

for reference here are the tests I added above https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/125/commits/9abc81d6ecb51bcabbbbf6644d5a247ddf854b9b
Added to your saved items
12:39
note that a KEY problem here is that there were NO unit tests for those two classes Hash_Json and Loops which is really bad since it doesn't allow for easy development of those classes, refactoring and error detection

-what I described above is the development pattern I explain here https://www.slideshare.net/DinisCruz/start-with-passing-tests-tdd-for-bugs-v05-22-sep-2016

- here is a refactoring using the OSBot_Utils apis

pic 1 before
pic 2 after
https://glasswall-solutions.slack.com/archives/C01SHLVNPRC/p1618693113260800 

- note: when possible sort the methods alphabetically

pic 1 - not sorted
pic 2 - sorted 


- here is a good example of a test that uses method patching to keep the test focus on the actual behaviour bing tested (in this case answering "is the Hash_Json data saved ok?")

- also note how it is really more than ok to have two lines of code being tested by 10 lines of test code (in fact I would expect us to have much more code in the testing than in the main codebase)

https://glasswall-solutions.slack.com/archives/C01SHLVNPRC/p1618741088267500 

- here is the commit with the code changes added in the creation of this Unit Test https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/125/commits/6d79380a6228e392547224036c15e41567f08d1b

**Testing best practices:**
- Document unit test process
- Document: https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/2380468987?check_suite_focus=true 

**General best practices:**
Delete not needed branches
Refactor/repo structure regarding folders (create template?)

**Comment by MaNe2020** [comment]
Started working on the doc: https://docs.google.com/document/d/1XmXj1Z2E703vKzMOqJLkSa7HAbgrUQDP90xFI5XSHog/edit?usp=sharing

All details are added it needs more restructuring. 

@GINAGC where should we have this avl?

**Comment by GINAGC** [comment]
@MaNe2020 we will create a repo for process documentation, we will share it soon.

**Comment by MaNe2020** [comment]
@GINAGC @chrisdiao 
take a look in this doc and let me know if any addition is needed.


https://docs.google.com/document/d/1XmXj1Z2E703vKzMOqJLkSa7HAbgrUQDP90xFI5XSHog/edit?usp=sharing

**Comment by GINAGC** [comment]
@MaNe2020 looks good. We can update to here https://github.com/k8-proxy/EAP-Docs/blob/main/Development/Development.md and have the team to review and send PRs as needed to update. 

@kekesimarti I remember seeing some other dev coding best practices, are they in the onboarding? please also include them.

**Comment by MaNe2020** [comment]
@kekesimarti great job in moving this to docs: https://github.com/k8-proxy/EAP-Docs/blob/main/Development/Development.md
Looks great. I will move this for the release as all work is done.
