### ISSUE TITLE
Generate Detail analysis of report.json

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder#139]
@ggrig as discuss please can we have csv generated from data folder which contain below column,

file name | file type | size | remediated item count | remediate items list | sanitised item count | sanitised items list | issue item count
-- | -- | -- | -- | -- | -- | -- | --

**Comment by DinisCruz** [comment]
This data needs to be calculated from the data in Elastic

**Comment by DinisCruz** [comment]
What we need here is to map what data is missing from Elastic in order to do this
