### ISSUE TITLE
Polyglot files support on file generator API 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#141]
@Samarth (Upwork - Python Developer) can you look at the code we had for creating Polyglot files and add that feature to this API (@Georgina Gonzalez (DM) can you put @Samarth (Upwork - Python Developer) in touch with the devs that were experimenting with Polyglot files)
https://github.com/filetrust/gw-proxy-serverless/tree/master/security/ployglot
https://github.com/filetrust/product-file-type-detection

**Comment by GINAGC** [comment]
Latest update: polyglots files are created but the engine dint processes them.

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #17](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/17) via [**ZenHub**](https://www.zenhub.com/)
