### ISSUE TITLE
Create flag that processing is currently happening

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#147]
Add flags or indication that processing is currently happening with additional info for what folder and what IP.

**Comment by GINAGC** [comment]
@MaNe2020 I dont think this is needed anymore, do we need it?

**Comment by MaNe2020** [comment]
@GINAGC not sure. I think it would be nice to have (not just by refreshing kibana dashboard) but as a part of the UI some info box.
Like:
"currently processing folder X
pls do not stop the processing if you want to start new one"

or smth more elaborate
