### ISSUE TITLE
Create heartbeat and health check tests to confirm the status of the Cloud SDK servers used

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#153]
create heartbeat and health check tests to confirm the status of the Cloud SDK servers used (we can use something similar to the random PDF generator used in the test below).

this is something that should run when we are doing large processing of files to make sure all is ok (checks should be done directly to the target servers and should affect data in hd2 or hd3)

**Comment by samarthdd** [comment]
I have added healthcheck /api/health on setting gw sdk IPs 

Which ever is not healthy wont be added to sdk endpoints

**Comment by MaNe2020** [comment]
@GINAGC as per @samarthdd comment, /api/health is tested and just healthy IPs will be added.
This functionality can be extended if health checks are needed during the run but that can delay the processing.
If something similar is needed new issue should be added.
