### ISSUE TITLE
Find a solution to save the elastic dashboards

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#155]
also we need a solution to save the elastic dashboards:

- https://www.elastic.co/guide/en/kibana/7.12/dashboard-import-api.html 
- set this up from an Jupyter notebook

**Comment by MaNe2020** [comment]
This is no longer needed. 
Dashboards are saved here: https://github.com/filetrust/cdr-plugin-folder-to-folder-test-data and automatically uploaded to UI.
Doc contains details on how to save them manually
