### ISSUE TITLE
Not well formed error during file processing

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#170]
High number of files end up in error as on the screenshot below
![image (4)](https://user-images.githubusercontent.com/70108899/115781524-cb995400-a3ba-11eb-96d7-cf89296c5b73.png)

**Comment by GINAGC** [comment]
@ggrig please take a look to this defect.

**Comment by ggrig** [comment]
The only case that the issue may take place is when the XML report obtained from the server is not of a parseable XML format.
That means the issue should be investigated on the GW SDK side.
All we can do here is to add more logging to ensure that is the case

**Comment by ggrig** [comment]
It turns out that the logging code has been added some time ago.
So the issue must be outdated
Will close it without modifications
