### ISSUE TITLE
GW SDK Read timeout errors

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#172]
Files not being processed due to: HTTPConnectionPool(host='GW SDK IP', port=8080): Read timed out. (read timeout=60)

**Comment by GINAGC** [comment]
@mohitsengarr can you take a look to this issue please?

**Comment by mohitsengarr** [comment]
> @mohitsengarr can you take a look to this issue please?

Sure @GINAGC

**Comment by mohitsengarr** [comment]
@MaNe2020 when are you getting this exception?

**Comment by MaNe2020** [comment]
@mohitsengarr this error is seen during CDR-folder-to-folder testing. 
The flow is, some number of files is being processed (by hitting GW SDK). And depending on the run, certain amount of files are being rejected by this error.
Deep debugging is not done but if you want we can setup a scenario so you can monitor specific GW SDK to see where and why this is happening.
Will also point you on the channel where you can see in pics of what is going on.

@GINAGC I am also not sure if this is issue with GW SDK or with the VM itself.

**Comment by GINAGC** [comment]
Thanks @MaNe2020. I think @samarthdd and @mohitsengarr can coordinate to debug this.

**Comment by samarthdd** [comment]
ok Let me check this. There are multiple factors which can affect this.
