### ISSUE TITLE
Instructions to resize the disk an AWS disk

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#190]
Capture the instructions to resize the disk an AWS disk somewhere. Please validate all commands before documenting them.

based on
here are the commands (I think) that worked
df -hT
lsblk
sudo growpart /dev/nvme0n1 1
sudo resize2fs /dev/nvme0n1p1

**Comment by MaNe2020** [comment]
@GINAGC this is already documented here: https://github.com/filetrust/cdr-plugin-folder-to-folder/wiki/6.-FAQ, #3
Will go one more time to verify it and split instructions for ESXI and AWS.
