### ISSUE TITLE
Import and export analysis files (namely hd2) 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#193]
import and export analysis files (namely hd2) - I think 90% of this was already there (I commented some of that code). note that we DONT want to export the source files, only the: metadata.json, analysis.json, report.json and status.json (per file in hd2)

**Comment by samarthdd** [comment]
@GINAGC This is merged .Please close this

**Comment by GINAGC** [comment]
@samarthdd sending back with this feedback:

Add 2 checkboxes: 1 for download all files as a default, 2 for all files except json

**Comment by samarthdd** [comment]
@GINAGC

**Comment by samarthdd** [comment]
@GINAGC to add to above

We discussed, it can be checkbox or -1 for all files.

I have pushed changes for the API with -1 to get all files.

**Comment by samarthdd** [comment]
there is no second checkbox, it is just that get all files in hash_folder except source file
