### ISSUE TITLE
Import zip to hd1 and hd2 folders 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#194]
import hd1 and hd2 folders (this will be a link to an url to download files to add to either hd1 or hd2

**Comment by ggrig** [comment]
The solutions add a pre-process API called "download_and_pre_process_a_zip_file"
This allows specifying a ZIP file URL that will be downloaded, extracted, and the files there will be pre-processed

**Comment by MaNe2020** [comment]
@ggrig can you pls give me an example. How this URL should look like
![image](https://user-images.githubusercontent.com/70108899/119119655-af291f80-ba2b-11eb-94ee-b05588cc44ba.png)

**Comment by MaNe2020** [comment]
@GINAGC I still need more info on this.
@ggrig pls provide an example of URL.

**Comment by kekesimarti** [comment]
@MaNe2020 provide the zip file in a URL.

**Comment by MaNe2020** [comment]
This one is really cool @ggrig 
Testing steps:
- Create folder and hd1 and hd2 subfolders
- Set above folder as default
- Go to Swagger, find an API as from pic below and pass the URL of the zip file you want to process (zip file anywhere from the internet).

![image](https://user-images.githubusercontent.com/70108899/119680626-a8424880-be41-11eb-8882-aead32dce4c6.png)

- Once API is executed, zip file will be unzipped and all files will be present and hd1 folder, they will also be pre-processed and present in hd2/todo folder

![image](https://user-images.githubusercontent.com/70108899/119680925-e93a5d00-be41-11eb-8e7b-c1bbc4c6a1b0.png)

Moving the issue `for release`
