### ISSUE TITLE
Import and export of kibana dashboards

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#195]

**Comment by MaNe2020** [comment]
@GINAGC as per Dinis implementation
dashboards are now uploaded to https://github.com/filetrust/cdr-plugin-folder-to-folder-test-data
and imported directly to UI with Metadata_Elastic.py
I have also added how to import/export dashboards as num 6 in FAQ.

Will move it to Release column so you can review it.
