### ISSUE TITLE
Write/Improve unit test coverage

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#196]
Raised #354 for this

**Comment by GINAGC** [comment]
For Mudit and Sanchit.

**Comment by gmuditdce** [comment]
Hi,
Added tests few days back, it went up by about 2% o ~82
Currently on
https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/286 should
have PR for this soon
Then I will move back to this again.
Thanks

**Comment by gmuditdce** [comment]
Added more tests via #419 
Actions run will fail, no endpoint available, default test server down, need to check and merge tomorrow

**Comment by MaNe2020** [comment]
this is constantly happening so will close this specific issue
