### ISSUE TITLE
Creat more sets/test scenarios

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#197]
Example:

100 MB
500 MB
1GB
2GB
5GB
10GB
etc
... 

- Also, please document all details for these test scenarios. 
- Document the test sets, add the links to the test sets in https://github.com/k8-proxy/data-sets

**Comment by GINAGC** [comment]
@dpatel7 in case that you have anything else to add here.

**Comment by MaNe2020** [comment]
@GINAGC I start adding this on cdr-plugin-marija2 (current IP: 52.211.64.9)
but I think we need a better place to collect these scenarios.

Here I added buckets with:
- 1000 files : 604MB
- 2000 files : 1GB
- 100 files : 60MB
- bucket with files that are all clean (no err during the run ~70files)
- bucket with files that have errors (~15 files)

and we have gov_uk that is ~7GB

Just let me know where to transfer them (some AWS bucket maybe?) or @dpatel7 do you have some better option?

As the main thing should be for these scenarios to be easily accessible and that they can be copied/transferred to any CDR VM (with some steps)

**Comment by GINAGC** [comment]
@MaNe2020 yes, to S3 buckets, please. So anyone can use them.

**Comment by MaNe2020** [comment]
S3 bucket created
CDR-Plugin-test-files: s3://cdr-plugin-test-files
- Folder 100 : 100 files, 60MB, different files types
- Folder 500 : 500 files, 375MB, subset of gov-uk
- Folder 1000: 1000 files, 604MB, subset of gov-uk
- Folder 2000: 2000 files, 1GB, subset of gov-uk
- Folder all-clean-73: 73 files, 40MB, folder 100 that contains just clean files

**Comment by GINAGC** [comment]
@MaNe2020 could you please add the links to the test data repo? and post them in channel too. Thank you!

**Comment by MaNe2020** [comment]
@GINAGC posted on the channel and details added to https://github.com/k8-proxy/data-sets
as we keep adding new files I will update repo accordingly. 
Will close this one.
