### ISSUE TITLE
Start sending metadata to elastic search

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#21]
Start sending metadata to elastic search

**Comment by GINAGC** [comment]
@ggrig to share the progress with Dinis.

**Comment by ggrig** [comment]
The branch for Elastic support is https://github.com/filetrust/cdr-plugin-folder-to-folder/tree/elastic_support
The commit that has working code is https://github.com/filetrust/cdr-plugin-folder-to-folder/commit/c7a760a4e3dd77201ef6b8a1c53e1a6203b55d9f#diff-43f70fc1fb96d9d[…]f7ca6aae7d36a4865da7

**Comment by DinisCruz** [comment]
This has been done
