### ISSUE TITLE
Document release process and create diagram (for all projects)

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#215]
- Make version tags automatically 
- Every push to main should have a version number (minor)
- From QA to release workflow.
- Once we have some features in ""to release"", tag an official release with all the features.
- Add labels with the version for each ticket on ""to release""
- Merging to main becomes automatically a pre-release and releases are going to be chosen for example once a week.
- distinguishing tags by code and pipeline
- Releases start with v0.0.1

**Comment by GINAGC** [comment]
duplicated with https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/218
