### ISSUE TITLE
Test and process all files from gov.uk - create dashboards with the results

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#217]
- Process all files from gov.uk
- Generate some dashboards showing all the results (for Samarth and Marija)

**Comment by MaNe2020** [comment]
@GINAGC run I executed yesterday 
25 threads, 10 GW SDKs
![image](https://user-images.githubusercontent.com/70108899/117449711-922b2180-af40-11eb-8d64-b559efee09e0.png)
![image](https://user-images.githubusercontent.com/70108899/117449928-d8808080-af40-11eb-8e4b-28873e6fb392.png)
![image](https://user-images.githubusercontent.com/70108899/117449978-ed5d1400-af40-11eb-987b-8dbcb4a3b5ca.png)

I think we can close this one?
