### ISSUE TITLE
Document release process and create diagram (for all projects)

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#218]
- Make version tags automatically 
- Every push to main should have a version number (minor)
- From QA to release workflow.
- Once we have some features in "to release", tag an official release with all the features.
- Add labels with the version for each ticket on "to release"
- Merging to main becomes automatically a pre-release and releases are going to be chosen for example once a week.
- distinguishing tags by code and pipeline
- Releases start with v0.0.1

**Comment by GINAGC** [comment]
@samarthdd lets sync on this task on Monday, I need your help on helping me to define the release process for all projects and create some diagrams about it.
