### ISSUE TITLE
mark-all-hd2-files-unprocessed

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#228]
Dinis Cruz (GW CTO and CISO)
btw, just noticed that we need a variation of the "clear-data-and-status-folder' which is something like 'mark-all-hd2-files-unprocessed' which basically moves back all files in the 'processed' folder back into the 'data' folder resets the metadata
deletes the other JSON files (events, report) this should be faster than copying the files again (which is what I have been doing, since that requires an actual file copy and the calculation of a file hash)

**Comment by ggrig** [comment]
This is a duplication of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/231

**Comment by MaNe2020** [comment]
Actual run 
![image (1)](https://user-images.githubusercontent.com/70108899/118441856-0d7f9680-b6ea-11eb-852c-0382afe7f3c2.png)
number of files in respective folders
![image](https://user-images.githubusercontent.com/70108899/118441879-1a9c8580-b6ea-11eb-996b-0d026b2bc5b9.png)

cannot_be_processed contains 12 files, should all 33 that failed be there?

**Comment by GINAGC** [comment]
@ggrig please check this one.

**Comment by samarthdd** [comment]
cannot be processed is outdated. its renamed to not supported now

**Comment by samarthdd** [comment]
this is working as expected

**Comment by samarthdd** [comment]
moves all not supported and processed files to todos

**Comment by MaNe2020** [comment]
Not sure if I understand this one still.
@samarthdd what about the files that ARE NOT PROCESSED, so where are now the files that are COMPLETED WITH ERROR?
not_supported is ok, also todo, but what about completed_with_error?
