### ISSUE TITLE
Expose more of the current functionality and workflows via the new docs site

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#235]
Expose more of the current functionality and workflows via the new docs site (which is really more of a UI for the app). Namely on the execution and visualization of the multiple scenarios

**Comment by MaNe2020** [comment]
Functionality exposed via PR: https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/468
Added new page in docs called `Additional Workflows` that has 6 sections/functionalities added in recents releases.

- Retry workflow
- uploading zip file via url
- setting number of threads for pre-processing
- checking cdr plugin/gw sdk version
- data on processing dashboard
- data on threat analysis dashboard

@chrisdiao @GINAGC will move this for you to review it
