### ISSUE TITLE
Reset the status of files in the 'completed with errors' state

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#239]
The good news is that we can try them again but without changing the status to 'initial' or even better 'retry' we can't see movement in the dashboard

This task is part of the improvements to the retry workflow.

**Comment by MaNe2020** [comment]
Testing steps: 

1. Process the files from one folder (clear, load, start)
2. Once processing is done, try again (start)

UI implication:
After step 2, `completed_with_error` counter is set back to zero
The rest stays the same, just this one is back to zero.
![image](https://user-images.githubusercontent.com/70108899/118443185-e4f89c00-b6eb-11eb-8851-351ae1eddfde.png)


@ggrig can you confirm above?
If so, this is tested, and `completed_with_error` count is reverted to zero on retry.

**Comment by GINAGC** [comment]
@MaNe2020 please open a separate bug for that, so it can be reviewed.

**Comment by samarthdd** [comment]
this is working as expected
