### ISSUE TITLE
Disable the creation of .html files until the retry workflow kicks in

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#240]
![image](https://user-images.githubusercontent.com/79467690/116862575-422d2180-ac05-11eb-8cca-7b8786a21449.png)

**Comment by MaNe2020** [comment]
Not sure what "until retry workflow means", but creation of HTML files is completely disabled. The files will not be created in HD3. Nor during original run, nor after retry workflow.

One way or another (original or retry run) HTML files will not be created.
