### ISSUE TITLE
We need a status called "Stopping"

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#242]
We need a status called "Stopping" for the period between calling the stop API method and all threads have stopped
![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/4abbfcdc-14c4-4efb-b7a9-6d3192b179e1)

**Comment by MaNe2020** [comment]
Tested and implementation is visible here
![image](https://user-images.githubusercontent.com/70108899/118445087-46216f00-b6ee-11eb-8a5f-b2d473175f90.png)
