### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#251]
Run tests that run against a running docker-compose or (when we have it) Kubernetes setup.
These tests can take a bit to execute (from 1 to 10 secs) and should be focused on invoking as much code as possible (although in some cases we also want to test specific functions directly).
We also need to capture the test coverage of this execution (not sure how coveralls will handle this).

**Comment by MaNe2020** [comment]
@dpatel7 check this one and comment if work has been done already.

**Comment by gmuditdce** [comment]
@MaNe2020 we have integration tests and in good numbers now. We can close this.
cc: @ggrig

**Comment by MaNe2020** [comment]
@chrisdiao based on above comment closing this one.
