### ISSUE TITLE
Get the direct link to a specific dashboard so that we can add it to a Hugo/website page

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#257]
Find a way to get the direct link to a specific dashboard so that we can add it to a Hugo/website page

**Comment by nishantswarup** [comment]
need more information.

**Comment by MaNe2020** [comment]
Will close this one as I think idea is the same as for this: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/469
