### ISSUE TITLE
Solve the current problem of how the UI can find which ports to use for the Iframes

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#258]
Solve the current problem of how the UI can find which ports to use for the Iframes

**Comment by nishantswarup** [comment]
are we looking configurable port to API, AWS API, Kibana servers

**Comment by jpoolGW** [comment]
I think the priority on this item should be increased to P1

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
