### ISSUE TITLE
Zip the current HD1, do couple of runs over several days

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#270]
Go to the ec2 instance called something like Dinis-large-cdr-plugin-workflow*and:
* zip the current hd1 (with 90Gb). I think this has all the file types we support except the large ppt.zip from https://downloads.digitalcorpora.org/corpora/files/govdocs1/by_type/ (which will be good to have)
* do a run (maybe over a couple of days using a couple of servers) to complete that run? 
* Try the new version of CDR platform
* Create a new hd1 folder with all the files that were rebuilt ok (there is a Jupyter notebook that helps with this)
* Put all of the above in S3

**Comment by MaNe2020** [comment]
VM: cdr-plugin-large-90gb-marija
Data are avl on VM itself and can be reused

threads: 100
GW SDK: 10
total duration: ~20h (with 5h break as seen on screenshots)
![image (9)](https://user-images.githubusercontent.com/70108899/117437231-39ec2380-af30-11eb-9bcf-72d5e4b1440a.png)
![image (8)](https://user-images.githubusercontent.com/70108899/117437237-3c4e7d80-af30-11eb-979e-bc557ee4adfe.png)
![image (7)](https://user-images.githubusercontent.com/70108899/117437249-3eb0d780-af30-11eb-9492-1135f9c009d3.png)

**Comment by MaNe2020** [comment]
Clean files copied to S3 bucket: s3://cdr-plugin-test-files/35_OK.zip, all clean files, 34.2GB
At the end 34.2GB
Info added to https://github.com/k8-proxy/data-sets/edit/main/README.md

Will close this ticket
