### ISSUE TITLE
Refactor how we use the file storage so that it is configurable with HD1, 2, 3, or local storage

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#271]
Refactor how we use the file storage so that it is configurable with HD1, 2, 3, or local storage (using something like MinIO)

**Comment by GINAGC** [comment]
@rajmbcoderx what is the status of this?

**Comment by rajmbcoderx** [comment]
@DinisCruz After doing some refactoring and testing with https://pypi.org/project/cloudstorage/, I do see that cloudstorage provides limited functionality compared to using standard file APIs. The cloudstorage API works with Minio/S3 and LocalStorage but provides really limited functionality when copying directory. I think the current implementation with integration with Rclone or Dropbox is better way to handle any cloud storage.

I tried to use cloudstorage API and it slowed down the directory copy as I had to iterate over each file to copy.
