### ISSUE TITLE
Look for ways to improve the performance of the pre-processing

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#272]

**Comment by ggrig** [comment]
This is about making pre-processing (phase 1) a multi-threaded operation like processing (phase 2)

**Comment by GINAGC** [comment]
@ggrig please add tag label.

**Comment by kekesimarti** [comment]
@ggrig Waiting for your label.

**Comment by ggrig** [comment]
@MaNe2020 

You can specify the number of pr-processor threads with the Swagger interface:

![image](https://user-images.githubusercontent.com/26714598/120308216-e7aae200-c2e4-11eb-9e2a-e0b4c0ea6d45.png)
