### ISSUE TITLE
Improve how we manage the Kibana dashboards

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#277]
Currently they are loaded programatically from [https://github.com/filetrust/cdr-plugin-folder-to-folder/blob/main/cdr_plugin_folder_to_folder/metadata/Metadata_Elastic.py#L94](https://github.com/filetrust/cdr-plugin-folder-to-folder/blob/main/cdr_plugin_folder_to_folder/metadata/Metadata_Elastic.py#L94)
See the pic as a reference:
![image](https://user-images.githubusercontent.com/79467690/117156446-fbcef280-adbd-11eb-87eb-3a6f5219d2de.png)

**Comment by MaNe2020** [comment]
@kekesimarti this is duplicate to https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/250 so I will close it.
