### ISSUE TITLE
website/content/docs/7. How to start?.md need to rename without ?

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder#278]
website/content/docs/7. How to start?.md  need to remove ? from file name. as is causing issue on windows.

**Comment by Lestat06** [comment]
@dpatel7 
PR created
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/279
or can i commit this directly since its a small change?

**Comment by DinisCruz** [comment]
I just merged it

btw we need to start making the new commits to develop branch not main

**Comment by Lestat06** [comment]
Correct. saw the slack msg after PR sorry about that.

**Comment by DinisCruz** [comment]
this has been fixed
