### ISSUE TITLE
Root of API should show the swagger page

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/cdr-plugin-folder-to-folder#281]
i.e. instead of 
![image](https://user-images.githubusercontent.com/656739/117224825-c7ccef00-ae08-11eb-854a-42487a04ab11.png)

show 
![image](https://user-images.githubusercontent.com/656739/117224838-d1565700-ae08-11eb-83f1-d648fb0e7df5.png)

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #18](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/18) via [**ZenHub**](https://www.zenhub.com/)
