### ISSUE TITLE
rename FastAPI to something like "GW Folder-to-Folder API"

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/cdr-plugin-folder-to-folder#282]
![image](https://user-images.githubusercontent.com/656739/117224901-fa76e780-ae08-11eb-95c3-389bd71a5e92.png)

**Comment by DinisCruz** [comment]
merged

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #19](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/19) via [**ZenHub**](https://www.zenhub.com/)
