### ISSUE TITLE
Add support for uploading files a zip file as the content of the file to add to hd1

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#286]
Add support for uploading files a zip file as the content of the file to add to hd1
for example, it should be able to upload and see expanded the zip I can download [Add support for uploading files a zip file as the content of the file to add to hd1](from https://github.com/filetrust/malicious-test-files)

![image](https://user-images.githubusercontent.com/79467690/117275876-c7f7d980-ae5e-11eb-8640-447260e0678f.png)

**Comment by GINAGC** [comment]
@gmuditdce can you take this?

**Comment by gmuditdce** [comment]
sure @GINAGC

**Comment by gmuditdce** [comment]
@dinis-cruz-gw @GINAGC @ggrig  Understanding from meeting on this is
1. We already have an endpoint that takes a url, downloads a zip from there and extracts it to hd1
2. We will add a query parameter to it to make the url download optional, if url is absent we will assume the zip if there in hd1 and unzip it.
Is that correct?

**Comment by MaNe2020** [comment]
@gmuditdce @ggrig I think this issue has been implemented? Pls confirm and closed if so.

**Comment by gmuditdce** [comment]
I think we have support for this
@ggrig can confirm and close..last known status is we have this.

**Comment by MaNe2020** [comment]
@chrisdiao based on above comment closing this one.
