### ISSUE TITLE
Download files from at least 5 websites and store them in S3

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#288]
Download files from at least 5 more websites and store them in S3.

- Glasswall website
- [https://downloads.digitalcorpora.org/corpora/files/govdocs1/zipfiles/](https://downloads.digitalcorpora.org/corpora/files/govdocs1/zipfiles/)
- Some other sites with GB of data.

**Comment by GINAGC** [comment]
@MaNe2020 I think you can take this.

**Comment by MaNe2020** [comment]
1. Any zip from https://downloads.digitalcorpora.org/corpora/files/govdocs1/zipfiles/ can be downloaded separately, also 35GB of clean files from this website is avl on: s3://cdr-plugin-test-files/35GB_OK.zip
2. https://www.fticonsulting.com/ files avl on: s3://cdr-plugin-test-files/fticonsulting.zip
3. http://www.bitsavers.org/bits/ files avl on: s3://cdr-plugin-test-files/bitsavers.zip
4. https://glasswallsolutions.com/ files avl on: s3://cdr-plugin-test-files/gwsolutions.zip
5. https://wikileaks.org/sony/docs/01/ files avl on s3://cdr-plugin-test-files/wikileaks.zip

**Comment by GINAGC** [comment]
@MaNe2020 excellent! please add to https://github.com/k8-proxy/data-sets - please add a table with the source, files on S3, total files, total size.

**Comment by MaNe2020** [comment]
Table created: https://github.com/k8-proxy/data-sets/blob/main/README.md
![image](https://user-images.githubusercontent.com/70108899/119811065-fa897500-bee6-11eb-815b-f0169dc8b7ff.png)

Will add pubic URLs once ready. 
And continue with testing on these datasets.

**Comment by kekesimarti** [comment]
@GINAGC Can we close this one?

**Comment by dpatel7** [comment]
@kekesimarti yes we can close it
