### ISSUE TITLE
Process the files from #288 and create reports of them

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#289]

**Comment by MaNe2020** [comment]
wikileaks run
![image](https://user-images.githubusercontent.com/70108899/119977781-1cebc300-bfb9-11eb-97ef-f8102a1db6df.png)
![image](https://user-images.githubusercontent.com/70108899/119977856-32f98380-bfb9-11eb-9a97-3b07dca1060f.png)

**Comment by MaNe2020** [comment]
bitsavers - using LB and 25 threads
![image](https://user-images.githubusercontent.com/70108899/119980394-7e616100-bfbc-11eb-9034-6e48b3f8bd6e.png)
![image](https://user-images.githubusercontent.com/70108899/119980597-caaca100-bfbc-11eb-964d-7973046df7b7.png)

**Comment by MaNe2020** [comment]
fticonsulting- LB, 25 threads
![image](https://user-images.githubusercontent.com/70108899/119985982-9f798000-bfc3-11eb-8808-fd0602595bba.png)
![image](https://user-images.githubusercontent.com/70108899/119986438-1f074f00-bfc4-11eb-8adf-4ff46e6724fd.png)

**Comment by MaNe2020** [comment]
Dataset: https://digitalcorpora.s3.amazonaws.com/corpora/files/govdocs1/zipfiles/000.zip
Using 5 GW SDKs with 50 threads
![image](https://user-images.githubusercontent.com/70108899/120182362-94666000-c20e-11eb-9495-bac6c4403499.png)
![image](https://user-images.githubusercontent.com/70108899/120182427-aba54d80-c20e-11eb-966b-cc1ef9bc12c3.png)

**Comment by MaNe2020** [comment]
gwsolutions, 5 GW SDK IPs, 50 threads
![image](https://user-images.githubusercontent.com/70108899/120185205-32a7f500-c212-11eb-9d09-a60c9f5a5c6f.png)
![image](https://user-images.githubusercontent.com/70108899/120185306-4eab9680-c212-11eb-9871-899e76de8f42.png)

**Comment by MaNe2020** [comment]
@kekesimarti @GINAGC this is all 5 runs with data from scarped websites.
Let me know if anything additional is needed here.

**Comment by GINAGC** [comment]
Thank you @MaNe2020. From here I will need the presentation that Marti is creating.
