### ISSUE TITLE
If autoscaling happens how CDR will assign new IPs

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#291]
If autoscaling happens how CDR will assign new IPs? We have that set IPs option but with AG it should be somewhat automatically. Try investigating AG but we need logic for CDR to pick that up.

**Comment by MaNe2020** [comment]
This is an outdated issue. The work is now done to set load balancer and check how it works.
Pls @chrisdiao @GINAGC confirm and if so just close it as it is not valid anymore.
