### ISSUE TITLE
Pressing "load files" a newly deployed AMI causes 500: Internal Server Error

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#292]
![image](https://user-images.githubusercontent.com/26714598/117309697-b7ae2180-ae93-11eb-9cb3-d282594287e5.png)

**Comment by GINAGC** [comment]
@ggrig, @MaNe2020 is this still an issue?

**Comment by MaNe2020** [comment]
@ggrig do you remember what were the steps you executed? 
I think it was click LOAD before CLEANING the folder? I can retry to verify

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #20](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/20) via [**ZenHub**](https://www.zenhub.com/)
