### ISSUE TITLE
The workflow website is not working in offline mode

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#303]
![image](https://user-images.githubusercontent.com/61416876/118475279-f77ecf80-b703-11eb-8de8-a78a83a7a981.png)
 On Offline mode when we try and open different page like set IPs or status. the Iframe display no value.

**Comment by GINAGC** [comment]
@kekesimarti what was not working here? the OVA install?

**Comment by GINAGC** [comment]
@dpatel7 can you test and add here more details on what is not working? thanks

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #12](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/12) via [**ZenHub**](https://www.zenhub.com/)
