### ISSUE TITLE
Investigate and fix pytest warnings

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#305]
![image](https://user-images.githubusercontent.com/26714598/117455027-c9f19380-af57-11eb-913a-2c8e6d9df64c.png)

**Comment by MaNe2020** [comment]
@ggrig how can I check this?
Or if this is on code level @GINAGC someone else should verify it.

**Comment by GINAGC** [comment]
@ggrig please confirm how Marija can test this one. Thanks
