### ISSUE TITLE
Error when accessing dev_notebooks from Hugo

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#306]
Open Hugo (localhost:8004 or IP:1313) navigate to Servers>Jupyter and select dev notebooks
Getting empty page 
![image (10)](https://user-images.githubusercontent.com/70108899/117458130-39f91d00-af4a-11eb-9a75-4ecdc027bf7d.png)

**Comment by GINAGC** [comment]
@gmuditdce can you take a look to this issue please?

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #21](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/21) via [**ZenHub**](https://www.zenhub.com/)
