### ISSUE TITLE
Dev notebook for creating folder with clean files needs modifications

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#307]
It needs some indication that files are coping and also as sudo priv is needed for operations if folder does not exist and it does not have right permissions set it will not copy them 
![image (11)](https://user-images.githubusercontent.com/70108899/117458428-96f4d300-af4a-11eb-93a8-7539469d54d5.png)

**Comment by GINAGC** [comment]
@samarthdd can you take this please?

**Comment by samarthdd** [comment]
yes on it

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #22](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/22) via [**ZenHub**](https://www.zenhub.com/)

**Comment by samarthdd** [comment]
@MaNe2020 Please test and close this issue if resolved
