### ISSUE TITLE
Threat intelligence report not showing the total

### ISSUE THREAD

**Issue by Lestat06** [filetrust/cdr-plugin-folder-to-folder#308]
It is showing the unique instances of risk level, instead of the total
![2k-threatLVL](https://user-images.githubusercontent.com/6232283/117460190-89404d00-af4c-11eb-81e4-d2efab2b1609.png)

**Comment by GINAGC** [comment]
@MaNe2020 can you take a look at this?

**Comment by MaNe2020** [comment]
@GINAGC this is related to issue @samarthdd is working on.https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/322 or https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/263

@Lestat06 @GINAGC we can close this one as there are 2 other that are connected to this.

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #23](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/23) via [**ZenHub**](https://www.zenhub.com/)
