### ISSUE TITLE
Make CK8s versions compatible to work offline in the GW Cloud SDK project

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#311]
When we start new OVA without internet access couple of services in fail status
![2021-05-06_14h56_43](https://user-images.githubusercontent.com/61416876/117633470-f7b42380-b175-11eb-8c6c-dda02bd80cbe.png)

**Comment by DinisCruz** [comment]
Hi, as part of the investigation of this issue, please add the details here

also see if we can write tests that replicate the current situation (i.e. tests that capture where the problem is)

**Comment by GINAGC** [comment]
Issue moved to GW Cloud SDK repo: https://github.com/k8-proxy/cs-k8s-api/issues/318
