### ISSUE TITLE
Create a set of deployment servers For Cloud SDKs:

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#315]
- a couple that are designed to be running for long periods of time (i.e. for days and for weeks) - this will allow us to see if there are issues (like the one that NYT just hit) that only occur after a while
- an auto-scaling group that is tied to a stable DNS entry (i.e. elastic IP) that can then be used as part of CI tests and for anybody that wants to test a F2F AMI/OVA and doesn't want to also start new Cloud SDKs

Please share the DNS entry above to the rest of the organisation and devs.

**Comment by GINAGC** [comment]
gw cloud sdks which will be running for weeks which can be used for long runs
34.247.215.4
3.250.230.76
3.249.162.165
Load balancer DNS for auto scaling group which listens in port 80
gw-cloud-sdk-455649808.eu-west-1.elb.amazonaws.com
