### ISSUE TITLE
Clear analysis_json data 

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#322]
when we create Threat Analysis dashboard that uses analyse_json, when data are cleared, this dashboard always stays, it does not get updated. I suspect it is due to fact we do not have timestamp field there and that is required so Kibana can parse it. 

Find a way to clean analysis_json

**Comment by MaNe2020** [comment]
video that show the issue in action: https://www.loom.com/share/c5ed52cf85a847a7a0a993088a3c0526

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #24](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/24) via [**ZenHub**](https://www.zenhub.com/)
