### ISSUE TITLE
Exposes data in Prometheus Data Format

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#324]
From @DinisCruz 

Hi, I did some research over the weekend on Prometheus and Hugo and here are some design and direction notes: (please update the respective issues, since some of the comments below provide more clarity in some of the issues)
**Using Prometheus**
(see this video for a great intro to Prometheus)

key concept: **Add native support for Prometheus to the entire application/solution and API**
In practice :point_up: means that we need to add to ALL our APIS (@Georgina Gonzalez (DM) this includes the CloudSDK) an /metrics endpoint that exposes data in Prometheus Data Format (we might also need an /healthz endpoint, this needs to be checked)

For example @Samarth (Upwork - Python Developer) and @Harut Grigoryan this means that we should be exporting our status and  monitoring data in this format (i.e, we need to refactor the existing code to reflect this). The  time-series data format used by Prometheus is very flexible and we can really used it to expose all sorts of metrics (below I call this time-series data)

We also need to expose Prometheus data from the base infrastructure: Kubernetes, Docker Compose, Host servers (for every server used in a solution) which will help a lot in understanding what is happening with the target servers
In terms of consuming this data,  at the moment I see 3 modes of operation:

- Mode A) direct consumption of time-series data exposed by endpoints. This is very similar with what we already do with the data exposed by the /processing/status and /configuration/config/ endpoints. In this mode the UI (or consumer) will call this directly and show that data directly to the user (this will be very useful in cases where there is not need to capture historical data). This task is for the Dev team
- Mode B) a prometheus server will collect this data at a regular interval (i.e. call the /metrics endpoint and store it in its time-series database. This data can then be accessed by multiple UIs: Prometheus UI, Grafana other javascript UIs that query the data stored in the Prometheus database using PromQL (note that Prometheus supports all wide set of Pull and Push architectures, where data can be easily moved from one instance of Prometheus to another). Note that in this mode the data in Prometheus should be considered to be ephemeral (i.e. not last very long). This task for the infrastructure team (namely starting by adding Prometheus and Grafana to docker-compose)
- Mode C) Collect data stored in one or many Prometheus servers using something like MetricBeat to save the data in a long-term-data-store and/or send it to Elastic (which would also allow Kibana to be used for visualisation of long term trends (see this article for more details)) . No task for now

What is key is for us to leverage the architecture and tools already available in the Prometheus ecosystem and implement a similar model in our tools

We also need to leverage the work that we have already done with the multiple Prometheus integrations and automatic generation of Grafana dashboards

**Comment by DinisCruz** [comment]
@ggrig what are your plans/ideas to tackle this?

**Comment by ggrig** [comment]
This is about adapting our metrics to become compliant with Prometheus formats (see https://github.com/prometheus/client_python/blob/master/README.md)
This has been partially implemented in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/391 for metrics in Status.py
A similar approach should be applied to events, metadata, hash.json, etc

**Comment by MaNe2020** [comment]
@samarthdd can you pick up this one? I am not sure if I can do proper verification without complete integration.

**Comment by samarthdd** [comment]
Sure on it

**Comment by chrisdiao** [comment]
Hello @samarthdd , any progress on this, please?

**Comment by samarthdd** [comment]
I can see standard Prometheus data in processing/metric API


<img width="1439" alt="Screenshot 2021-06-03 at 3 22 36 PM" src="https://user-images.githubusercontent.com/64204445/120626337-304ad280-c480-11eb-9891-17e57d4f3640.png">

So we are getting data in Prometheus data format

Moving it to release since we are able to expose data in required format.

**Comment by samarthdd** [comment]
<img width="1404" alt="Screenshot 2021-06-03 at 3 28 13 PM" src="https://user-images.githubusercontent.com/64204445/120626611-730caa80-c480-11eb-8fb8-3280bfe1e33f.png">
