### ISSUE TITLE
Create a process that watches changes on hd1 and adds new files to hd2

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#325]

**Comment by chrisdiao** [comment]
@ggrig , may we know the PR for this, please. if you can link it from here, much better.

**Comment by DinisCruz** [comment]
hi looking at how this is implemented we need a better way to detect the file changes

**Comment by chrisdiao** [comment]
PR - https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/475

**Comment by chrisdiao** [comment]
This has been included in v0.11.0 release
