### ISSUE TITLE
Investigate GW SDK err "Report xml not exist for file"

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#326]
This is intermittent issue but during file processing file does not end up processed successfully due to "Report xml not exist for file".
If flow is retried it can end up build successfully but the question is what was wrong at the first place.

**Comment by GINAGC** [comment]
@MaNe2020 please add a sample file for this to be duplicated.

**Comment by MaNe2020** [comment]
@GINAGC the thing with this one is that is can happen to any file. Here is one I had the issue, but on re-run and re-try this went smoothly
[CalcTest.xls](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6465860/CalcTest.xls)

**Comment by GINAGC** [comment]
@mohitsengarr can you take a look to this?

**Comment by mohitsengarr** [comment]
@MaNe2020 Can i know the endpoint please?

CC: @GINAGC

**Comment by GINAGC** [comment]
@MaNe2020 to confirm endpoint.

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #25](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/25) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GINAGC** [comment]
@MaNe2020 can you confirm the endpoint for this issue?

**Comment by MaNe2020** [comment]
@mohitsengarr @GINAGC I tried during this few days to find the similar output but without luck.
The original endpoint is long gone and files are now failing with different errors. 
Can we leave this in backlog and in case it comes up again I will add comment

**Comment by MaNe2020** [comment]
@mohitsengarr @GINAGC I was finally able to get more details on this but the best (and maybe the only way) to test and fix this is, by actually using CDR Platform and running some files.

Run govUk dataset, and parsed all error.json files. There was 168 errors `Report xml not exist for file` in set that ended with 605 total errors.

Here is error.json analysis txt , [final.txt](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6515543/final.txt)

Attaching also 2 files that I tracked
[traffic-sign-drawing-schedule-12-part-20-item-22-p617.pdftraffic-sign-drawing-schedule-12-part-20-item-22-p617.pdf](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6515547/traffic-sign-drawing-schedule-12-part-20-item-22-p617.pdftraffic-sign-drawing-schedule-12-part-20-item-22-p617.pdf)

And: https://github.com/k8-proxy/data-sets/blob/main/FilesWithIssues/London_B_Panel_Web_Version_List-3-September-2020.docLondon_B_Panel_Web_Version_List-3-September-2020.doc


IPs used are part of ASG: cdr-plugin-dev-sdk-asg
Using AMI: ami-02cbabf0a1433ab25
Today IPs are: ["54.216.22.136", "54.77.218.13", "3.249.99.117", "52.31.32.110", "54.170.210.157", "34.245.159.227", "34.250.197.139", "52.48.94.108", "34.253.136.74", "34.244.154.96"]

**Comment by mohitsengarr** [comment]
Testing this defect as usual and this issue was specific to the minio-version. In minio-version for report xml, have the different process than the classic. So, now GW SDK is handling that it.   @GINAGC

**Comment by Lestat06** [comment]
This error doesnt occur with cs-api-sdk. tested with different scenarios in cdr-f2f whih included the files Marija has attached above.
we will test this with minio also
FYI @samarthdd

**Comment by samarthdd** [comment]
Yes this is not occuring now. I think this was happening in earlier AMI due to minio was not keeping files for only few minutes and no it is increased to 10 min

**Comment by samarthdd** [comment]
@mohitsengarr 

this issue is happening on api
/api/analyse/rebuild-zip-from-file
/api/analyse/rebuild-zip-from-base64

use dotx files to replicate.

I have posted sample files in channel

**Comment by mohitsengarr** [comment]
@samarthdd the issue `"Report xml not exist for file"` is for the classic version for dotx file. This issue is because classic version is returning the `Rebuild` status but not generating the xml file for the dotx file. For this issue adaption-service has to be investigated why report xml is not being generated for dotx file even the status is `rebuild`.

![image](https://user-images.githubusercontent.com/43764140/121535841-21d05e00-ca20-11eb-9298-603292a44426.png)

FYI @GINAGC

**Comment by GINAGC** [comment]
@samarthdd to retest after https://github.com/k8-proxy/go-k8s-process/issues/73 is fixed

**Comment by samarthdd** [comment]
https://github.com/k8-proxy/data-sets/blob/main/dotx/Issue_0501003A_No_Sanitisations.dotx

**Comment by Lestat06** [comment]
this one throws the same error also. it should say GW_ERROR
[Office2016_Issue0501002F.docx](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6656722/Office2016_Issue0501002F.docx)

**Comment by mohitsengarr** [comment]
@samarthdd @Lestat06 This issue is happening for classic version and it's not the issue in `cs-k8-api` but it is in `icap-adaptation-service`. `icap-adaptation-service` is returning the rebuilt status but not generating the xml for the same. @GINAGC Issue should be open for the `icap-adaptation-service` repository.

**Comment by samarthdd** [comment]
Yes its happening only for classic version and yes I agree it is ICAP related issue. 

probably icap-adaptation-service is the repository

@GINAGC what is the step for this, Can we move this to respective repo? This is not cs-k8s-api issue

**Comment by mohitsengarr** [comment]
@GINAGC For this need to investigate the `icap-adaptation-service` and would be done in around 4 days.

**Comment by mohitsengarr** [comment]
@GINAGC I have investigated this issue and found that some files(.dotx,docx) are being detected as a zip file by the `GW Engine` itself. But it shouldn't be detected as zip. Please see the logs of `adaptation-service`. That is causing the issue in classic version.

![image](https://user-images.githubusercontent.com/43764140/124510960-9665a500-ddf2-11eb-9209-0c2c72adba1a.png)

**Comment by GINAGC** [comment]
Thank you @mohitsengarr 

@MaNe2020 please open an issue for the core team https://github.com/filetrust/sdk-rebuild-eval/ with all possible details. Thank you

**Comment by MaNe2020** [comment]
@GINAGC issue has been created: https://github.com/filetrust/sdk-rebuild-eval/issues/9
Pls change this one to corresponding status.

**Comment by GINAGC** [comment]
Blocked until internal issue is resolved filetrust/sdk-rebuild-eval#9
