### ISSUE TITLE
Investigate GW SDK error " Document Access Blocked due to Policy"

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#327]
Multiple files end up not being processed successfully with above error
we should investigate what is causing it

**Comment by GINAGC** [comment]
@MaNe2020 can you add a sample file that is causing this? so dev can use it as a reference.

**Comment by MaNe2020** [comment]
@GINAGC @mohitsengarr
File that has "Document Access Blocked due to Policy" on file-drop returns
![image](https://user-images.githubusercontent.com/70108899/118138899-239a0800-b407-11eb-8baf-ffdb7b12180d.png)

Sample file 
[tab-6--compromise-settlement-agreement-and-mutual-general-release-fully-execut.pdf](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6473002/tab-6--compromise-settlement-agreement-and-mutual-general-release-fully-execut.pdf)

**Comment by MaNe2020** [comment]
Same is for files larger than 3.5MB
![image](https://user-images.githubusercontent.com/70108899/118140356-95bf1c80-b408-11eb-80b4-fdc4cc4ccd60.png)

Sample file is surfstitch-group-limited---noni-b--asx-announcements.pdf and it is uploaded https://github.com/k8-proxy/data-sets/tree/main/FilesWithIssues
[surfstitch-group-limited---noni-b--asx-announcements.pdf](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6473080/surfstitch-group-limited---noni-b--asx-announcements.pdf)

**Comment by mohitsengarr** [comment]
@GINAGC This is not the issue of GW clousd SDK. This file isn't supported by GW rebuild Engine and engine is returning the error like "Document Access Blocked due to Policy" @MaNe2020

**Comment by MaNe2020** [comment]
@mohitsengarr why on file-drop this error is more elaborate?
@ggrig this means all files "Document Blocked due Policy" should fall in not-supported, but not as "file type not supported" but rather general not supported.
@GINAGC we need to tag this file somehow better.

**Comment by mohitsengarr** [comment]
you mean "unable to protect file due to structural issue" message on file drop? @MaNe2020 
This message is telling to the end user that this file couldn't be sanitizes/protected.

**Comment by GINAGC** [comment]
Lets discuss this on the next call.

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #26](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/26) via [**ZenHub**](https://www.zenhub.com/)

**Comment by GINAGC** [comment]
@kekesimarti please move this issue with comments and screenshots to https://github.com/k8-proxy/k8-rebuild-file-drop/issues

**Comment by GINAGC** [comment]
@ggrig this one is a bit of research to check what additional information we can provide to make the message more clear, instead of only displaying "document access blocked due to policy"

**Comment by GINAGC** [comment]
this will be handled in Filedrop project.
