### ISSUE TITLE
Running API Call /pre-processor/pre_process_folder causes test data in source location (hd1) to be deleted

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/cdr-plugin-folder-to-folder#344]
**Repro Steps**
- Set Target folders in /configuration/configure_env/
- Ensure hd2 is clear of any pre existing data
- Set Target folder to copy to hd2 using /pre-processor/pre_process_folder
- Check data folder in hd2
- Check source data in had1

**Expected Results:**
- Data is copied from hd1 location to hd2 data folder
- Source data is still available in hd1

**Actual Results:**
- 200 response code is seen
- Data shows **null**
- Data is not visible in hd2/data
- Data in source folder (hd1) is now missing

![2021-05-13_16h29_11](https://user-images.githubusercontent.com/60877176/118149479-7e346380-b409-11eb-9809-a9687b639a09.png)
![2021-05-13_16h29_18](https://user-images.githubusercontent.com/60877176/118149481-7eccfa00-b409-11eb-9b32-6b91cd6c6a74.png)
![2021-05-13_16h29_28](https://user-images.githubusercontent.com/60877176/118149483-7eccfa00-b409-11eb-8b43-a7d9ee39dbad.png)

**Comment by ggrig** [comment]
@jpoolGW 

What is the AMI number that exposes the issue?

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #27](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/27) via [**ZenHub**](https://www.zenhub.com/)
