### ISSUE TITLE
Create a table of versions, their limitations, and flows of how it works.

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#347]

**Comment by MaNe2020** [comment]
@samarthdd pls share doc here once you start working on this.

**Comment by GINAGC** [comment]
I am assigning this to @Lestat06 to support here, we can discuss later.

**Comment by MaNe2020** [comment]
Working doc: https://docs.google.com/spreadsheets/d/1c0ucev8FLUAxdMRDWWMMmrvHe7UtwSQrV-loRiJVbYw/edit?usp=sharing

**Comment by GINAGC** [comment]
I dont think this is needed anymore.
