### ISSUE TITLE
Increase CDR Plugin OVA/AMI protection

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#348]
To ssh to CDR Plugin we are now use username/pass both being plain username and plain password, kind of obvious. 
We need to change this, start using pem key or bastion or harder passwords.

**Comment by GINAGC** [comment]
@pranaysahith can you take a look to this please?

**Comment by pranaysahith** [comment]
@GINAGC  @MaNe2020  we have add a github secret "SSH_PASSWORD" in the repo with a strong password and packer will automatically use it during build.

**Comment by kekesimarti** [comment]
Issue moved to [filetrust/cdr-plugin-folder-to-folder-bugs #1](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/1) via [**ZenHub**](https://www.zenhub.com/)
