### ISSUE TITLE
Change "Completed OK" and "Completed with Errors" 

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#353]
In files_metadata we currently tag each file that gets processed as "Completed OK" and files that are not processed as "Completed with error".
From user perspective this can be misleading as "Completed OK" does not mean that files were ok, it means that rebuild was done. And also "Completed with error" does not mean that there was smth with file, rather that GW SDK could not process it.

To make it more customer oriented we should add tags like "ORIGINAL FILE IS CLEANED", "ORIGINAL FILE WAS ALREADY CLEAN" and "UNABLE TO CLEAN FILE" to make it more comprehensive.

@GINAGC @DinisCruz what do you think?

**Comment by GINAGC** [comment]
Reopening so it is tested.
