### ISSUE TITLE
Add tag in files_metadata for files that were originally clean 

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#356]
If original file was clean add tag that indicates that.
This way we can have better number about files that were rebuild and the ones that did not need any modification

**Comment by kekesimarti** [comment]
Done

**Comment by MaNe2020** [comment]
This has been implemented 
![image](https://user-images.githubusercontent.com/70108899/119800075-f5bfc380-bedc-11eb-976b-46f046ca2c75.png)
Moving to `for release`

Created new issue just to have better naming: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/39
