### ISSUE TITLE
Integration of prometheus into docker compose

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#367]
Here is the sample file
https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml

That one references configurations in the https://github.com/vegasbrianc/prometheus repo, so to start it one needs to clone the repository

From Harut: However, it did not work on Ubuntu 20 for me

**Comment by Girish-pingala** [comment]
Follow below steps to test in Ubuntu 20.04 LTS Server: 

git clone https://github.com/filetrust/cdr-plugin-folder-to-folder.git --branch docker-compose-extends --recursive && cd cdr-plugin-folder-to-folder
cp .env.sample .env
echo "PWD=/home/ubuntu/cdr-plugin-folder-to-folder" >> .env
docker-compose -f docker-compose -f infra/docker-compose/jupyter-compose.yml up -d
docker-compose -f docker-compose -f infra/docker-compose/est01-kibana-compose.yml up -d
docker-compose -f docker-compose -f infra/docker-compose/website-compose.yml up -d
docker-compose -f infra/docker-compose/prometheus/docker-compose.yml -f infra/docker-compose/prometheus/promethgrafana-compose.yml up -d
docker ps

**Comment by GINAGC** [comment]
@ggrig, @samarthdd please QA this and add to the documentation.

**Comment by ggrig** [comment]
@GINAGC 
Currently, the files in infra/docker-compose needed to run the commands are not present.
So, all the commands fail

**Comment by ggrig** [comment]
@GINAGC 
This does not work for me:

docker-compose -f infra/docker-compose/prometheus/docker-compose.yml -f infra/docker-compose/prometheus/promethgrafana-compose.yml up -d
ERROR: Version mismatch: file ./infra/docker-compose/prometheus/docker-compose.yml specifies version 3.3 but extension file ./infra/docker-compose/prometheus/promethgrafana-compose.yml uses version 3.7

When changing the version in ./infra/docker-compose/prometheus/docker-compose.yml to 3.7 I get another error:

docker-compose -f infra/docker-compose/prometheus/docker-compose.yml -f infra/docker-compose/prometheus/promethgrafana-compose.yml up -d
ERROR: The Compose file './infra/docker-compose/prometheus/docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'extends'

**Comment by kekesimarti** [comment]
@dinis-cruz-gw please give some guidance on this issue.

**Comment by Girish-pingala** [comment]
These steps worked fine in Ubuntu 20.04 and Harut tried in 20.10 and have some issues. He is trying now on 20.04.

**Comment by ggrig** [comment]
@Girish-pingala 
I get the same errors on Ubuntu 20.04
![image](https://user-images.githubusercontent.com/26714598/120162436-6e8a8c80-c209-11eb-8b7f-29164b27ee03.png)

**Comment by Girish-pingala** [comment]
@ggrig , Hi Harut, I tried on my VMWare Workstation as well and it is working fine. Please find below steps followed, 
Steps followed on VMWare Workstation:
Download ubuntu iso from - https://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso
Create Virtual Machine using downloaded iso and login,
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
git clone https://github.com/filetrust/cdr-plugin-folder-to-folder.git --branch docker-compose-extends --recursive && cd cdr-plugin-folder-to-folder
cp .env.sample .env
echo "PWD=/home/ubuntu/cdr-plugin-folder-to-folder" >> .env
docker-compose -f docker-compose.yml -f infra/docker-compose/jupyter-compose.yml up -d
docker-compose -f infra/docker-compose/prometheus/docker-compose.yml -f infra/docker-compose/prometheus/promethgrafana-compose.yml up -d

![image](https://user-images.githubusercontent.com/78961055/120180796-d650cf80-c229-11eb-9f46-d29018acd35a.png)
![image](https://user-images.githubusercontent.com/78961055/120180847-e8cb0900-c229-11eb-97a2-0eea20b7c4a1.png)
![image](https://user-images.githubusercontent.com/78961055/120180898-f6808e80-c229-11eb-851e-b4c6e342c6cc.png)

**Comment by ggrig** [comment]
I get the same error as with Ubuntu 20.04 desktop
![image](https://user-images.githubusercontent.com/26714598/120301723-34d78580-c2de-11eb-9292-6e6541bc4037.png)

**Comment by ggrig** [comment]
Here is the full log of the commands run from the SSH terminal 

[Ubuntu 20.04 Terminal.log](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6575157/Ubuntu.20.04.Terminal.log)

**Comment by ggrig** [comment]
Prometheus works. The error above is not preventing it from being lunched

**Comment by ggrig** [comment]
Hi @GINAGC 
The solution provided by @Girish-pingala has been verified on my side.
This does start the Prometheus server in docker-compose.
The point here is to verify the solution does not break other functionality we have in docker-compose
I believe this should be done with intensive testing in QA, not in Dev

**Comment by Girish-pingala** [comment]
We are able to deploy all packages including Prometheus. Below are the steps,

git clone https://github.com/filetrust/cdr-plugin-folder-to-folder.git --branch docker-compose-extends --recursive && cd cdr-plugin-folder-to-folder
cp .env.sample .env
echo "PWD=/home/ubuntu/cdr-plugin-folder-to-folder" >> .env
docker-compose up -d

**Comment by ggrig** [comment]
@Girish-pingala 
Could you try building an AMI that includes the updated way of starting docker-compose and verify that it does start all the services including Prometheus?

**Comment by Girish-pingala** [comment]
@ggrig Please find the AMI : ami-0ce460611590df420 , it start all services including Prometheus automatically.

**Comment by MaNe2020** [comment]
@ggrig @Girish-pingala how can I access Grafana from the CDR Plugin VM deployed on AWS?
I can see Prometheus is started but I do not see info on how we should access it and verify the content. Pls add 
![image](https://user-images.githubusercontent.com/70108899/122100328-57f05200-ce13-11eb-9c3d-1ca2697a6897.png)


I tried with local forward and directly using IP:PORT but was not able to do so

@chrisdiao FYI

**Comment by Girish-pingala** [comment]
@MaNe2020 There is no Grafana in this deployment. You can access Prometheus using local-IP:9090 .

**Comment by MaNe2020** [comment]
@chrisdiao @GINAGC do we have task/plans to include Grafana also? And Harut mentioned we do not export Prometheus metric to the Prometheus server yet. If not task for that should be also created.

Thanks @Girish-pingala, verified and Prometheus Server is also exposed on 9090.

Moving this to release. @chrisdiao pls review above point and future tasks.

**Comment by chrisdiao** [comment]
Hi @MaNe2020 , this is well noted. [this](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/509) task has been created for that.
