### ISSUE TITLE
Create a presentation called something like “Glasswall analysis of 9k /6Gb files from Gov.Uk"

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#394]
Include:

1. Performance stats like # of servers, # of threads, average bandwidth per minute, average requests per minute, how long it took, how much it cost to do this run (in AWS compute costs)
2.  An analysis of files processed (I.e. what files were analyzed)
3. Current Kibana based threat analysis (like you have) and expand it to focus on those files with high risk (I.e. I want to see a list of what those files are and analyze them).

**Comment by MaNe2020** [comment]
Here is the ppt link: https://docs.google.com/presentation/d/1RrPohP9ad8q5wdy1siS4n_CyFKXxc4a4kvdSX3xiBcg/edit?usp=sharing
It will be updated daily.

**Comment by MaNe2020** [comment]
@GINAGC @kekesimarti I think we can close one. This ppt exists and in case of need we can always add more data to it. Moving you to Review so you can both take a look.

**Comment by GINAGC** [comment]
yes, I think this is done for now.
