### ISSUE TITLE
Find a way to track those high risk files to the url we downloaded them from 

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#395]
Ideally which page was linking to them. 
Questions: 
1. are these ALL files current available from [gov.uk](gov.uk)
2. Is it worth doing another data capture?

For these ‘high-risk files’ sync with @Harry Georgiou (GW Developer) to see how we can use the tool he is creating for checking the hash with VirusTotal.

**Comment by MaNe2020** [comment]
This is the list of high threat files
[discover-file-analysis.txt](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6523347/discover-file-analysis.txt)

the names are doubled (like marija.pdfmarija.pdf instead just marija.pdf), but disregarding that if correct name is searched in google it leads directly to the page where we downloaded it

SEARCH: https://www.google.com/search?q=legal-aid-crm15c.pdf&rlz=1C1GCEB_enRS840RS840&oq=legal-aid-crm15c.pdf&aqs=chrome.0.69i59l2.4167j0j7&sourceid=chrome&ie=UTF-8

Result
![image](https://user-images.githubusercontent.com/70108899/119157235-42c31600-ba55-11eb-92d8-ed0d7d722fc9.png)


@kekesimarti @GINAGC 
let me know if any additional work is needed for this

**Comment by DinisCruz** [comment]
humm, I noticed that 'double filename before' looks like a bug on how the files were created in the first place

**Comment by MaNe2020** [comment]
Issue created: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/423
@GINAGC not sure if this is the right project for it, but someone should review.

**Comment by GINAGC** [comment]
@MaNe2020 please document this on repo, probably in the data-sets?

**Comment by MaNe2020** [comment]
@GINAGC added
![image](https://user-images.githubusercontent.com/70108899/119799402-4f73be00-bedc-11eb-9928-8dd9f1239f1c.png)
