### ISSUE TITLE
Save/export all metadata files in a zip (I.e. H2 data without the source file)

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#396]
This way we can load it in a separate F2F server and have other teams looking and analyzing that data

**Comment by MaNe2020** [comment]
HD2 `processed` and `not_supported` folders, without source file, from govUk data set zipped and uploaded to S3: s3://cdr-plugin-test-files/govUk_hd2.zip

Cmd for cleaning, from HD2: `find . -name source -type f -delete`

**Comment by kekesimarti** [comment]
@GINAGC please take a look at this.
