### ISSUE TITLE
Create a list of the files we need to do further analysis (from a threat intelligence point of view)

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#397]
basically files with: Macros, JavaScript, comments, URLs, metadata, acroforms (you can sync up with @Petra Vukmirovic and @Elvin White to see what other good signals we can look for in the report.xml files)

**Comment by MaNe2020** [comment]
Here is the list of files with high threat level 

[discover-file-analysis.txt](https://github.com/filetrust/cdr-plugin-folder-to-folder/files/6523260/discover-file-analysis.txt)

**Comment by GINAGC** [comment]
@MaNe2020 what is the best place to upload this? probably to the data-sets mapping?

**Comment by MaNe2020** [comment]
@GINAGC best would be S3 since I think it will be 100 files so it can get heavy for gitHub.
Will share link once I create that sub folder.

**Comment by MaNe2020** [comment]
@GINAGC @kekesimarti
govUK files that are marked as the ones with HIGH threat level, 88 of them are copied to S3 bucket: s3://cdr-plugin-test-files/high_threat_govUk/

Info also added to data-set repo. 
Will moved this one to release QA and assign to you.

**Comment by GINAGC** [comment]
Thanks,
