### ISSUE TITLE
Once we have the list of files (#395-#397) use tools like pdfinfo to extract metadata and JavaScript

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#398]
* Pdfinfo:  [ https://hub.docker.com/r/gkmr/pdf-tools](https://hub.docker.com/r/gkmr/pdf-tools)
* Described here:  [https://stackoverflow.com/questions/29342542/how-can-i-extract-a-javascript-from-a-pdf-file-with-a-command-line-tool ](https://stackoverflow.com/questions/29342542/how-can-i-extract-a-javascript-from-a-pdf-file-with-a-command-line-tool)
* Another great tool to use is:  [ https://tika.apache.org/](https://tika.apache.org/)

Reach out to  @Elvin White @Greg Mann (GW) to see what tools they have to extract data from files

**Comment by MaNe2020** [comment]
Tool suggestion from Elvin: https://www.miraplacid.com/mtd/sdk.shtml

I will run high threat files from govUk through:
- https://www.miraplacid.com/mtd/sdk.shtml
- https://hub.docker.com/r/gkmr/pdf-tools
- https://tika.apache.org/
- CDR Plugin

and compare results
will create doc after this is done.

**Comment by chrisdiao** [comment]
Issue moved to [filetrust/cdr-content-integrity #35](https://github.com/filetrust/cdr-content-integrity/issues/35) via [**ZenHub**](https://www.zenhub.com/)
