### ISSUE TITLE
Download data sets from these websites

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#401]
1. [Wikileaks](https://wikileaks.org/sony/docs/01/)
2.  [ http://www.bitsavers.org/bits/](http://www.bitsavers.org/bits/)

**Comment by MaNe2020** [comment]
Files downloaded.
Info added to https://github.com/k8-proxy/data-sets/blob/main/README.md
![image](https://user-images.githubusercontent.com/70108899/119806701-bc8a5200-bee2-11eb-8dc1-108e52411940.png)

Files avl in S3 bucket:
s3://cdr-plugin-test-files/wikileaks.zip
s3://cdr-plugin-test-files/bitsavers.zip
