### ISSUE TITLE
Check what's hapenning inside the "test_server_status"

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#402]
Who reported: Dinis
- the objective of the `get_server_status` is to: 
a) call self.get_server_data() under a lock (to prevent multiple threads from calling ) and 
b) save the data
- BUT, the `test_server_status` is not testing for that lock and the save (that test is mainly testing the changes made by `get_server_data`
- also shouldn't the `self.save()` happen before the lock? 
Question: What is that lock actually doing here?

Reference:
![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/044bf55f-8156-4515-a21f-37df6189ff1a)

**Comment by ggrig** [comment]
Currently, the test has been renamed to 'test_get_server_data' which better reflects the purpose of the test.
That is, it tests that the 'get_server_data' method does get info about the server (CPU utilization, RAM utilization, etc)
This is not supposed to test Python locking or file Saving mechanisms
Closing the issue as not relevant
