### ISSUE TITLE
Analyse the reason of the time in step which takes place before any file is sent to the SDKs

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#405]
Reported by: Dinis
Hi, please see below a number of screenshots I took on a test run l did yesterday (well early this morning) of the 6.83 GB / 9.7k files from gov.uk

**Some analysis of the images:**

(pic1)  it takes about 6 minutes to pre-process the files (from hd1 to hd2) - where this server was processing about 1400 files per minute (which is still very slow and not really taking advantage of all the compute available in the server)
![image](https://user-images.githubusercontent.com/79467690/119000763-b0a30b00-b98b-11eb-8612-6c98a44c1dff.png)

(pic1, pic2, pic3, pic4), once files are in hd2, and we press 'start' there is another (even slower) step that takes place before any file is sent to the SDKs. You can see this by the average files processed now being about 700 per minute (which is basically something being changed with the files still in the 'Initial' stage). this process takes about 13 minutes (which you can see finally starting at pic4, 21 minutes after the process started)
![image](https://user-images.githubusercontent.com/79467690/119001031-ea741180-b98b-11eb-8556-62064663382f.png)
![image](https://user-images.githubusercontent.com/79467690/119001089-f65fd380-b98b-11eb-8514-7d90ca720210.png)
![image](https://user-images.githubusercontent.com/79467690/119001154-02e42c00-b98c-11eb-89c7-6c6ffc024476.png)

This run was done against the minio version with 5 hot pods, where I was running 60 t3.xlarge servers and 240 threads
With these servers we where averaging about 400 files per minute, 6.6 files per server per minute, and an average process time of ~13 seconds (we really need to look at the performance indicators of the F2F server, since I think this minio version have much more capacity (for example when running just one server I was able to get about 25 files per minute from one server, with 3 to 7 secs process time, which means that I should be able to get about 1500 files per minute with 60 servers)
pic8 shows that the entire processing (of stage 2) took 2,392 seconds, i.e. 39 minutes
![image](https://user-images.githubusercontent.com/79467690/119001232-15f6fc00-b98c-11eb-8fe5-0fe25142c7b3.png)
![image](https://user-images.githubusercontent.com/79467690/119001290-21e2be00-b98c-11eb-830b-b8dcd3308eff.png)
![image](https://user-images.githubusercontent.com/79467690/119001344-2dce8000-b98c-11eb-8f30-cc46e655eed9.png)
![image](https://user-images.githubusercontent.com/79467690/119001396-39ba4200-b98c-11eb-95a0-3c6d92f06ece.png)

**Comment by ggrig** [comment]
The time period is spent on compiling the hash.json file for the processing session
This has been verified by updated events logged in hd2/status/events.json
A way to improve that may be to make the compilation of hash.json a multithreaded operation

**Comment by GINAGC** [comment]
@ggrig should this one be in QA? if yes, please add a comment on what to verify.

**Comment by MaNe2020** [comment]
Processing that was happening when pressing `START` is no longer present. 
This is the same as: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/38

As there is separate issue for improvements  on pre-processing will move this one and above one for release.
