### ISSUE TITLE
Do a similar run to this one every day

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#407]
Reported by: Dinis
Hi, please see below a number of screenshots I took on a test run l did yesterday (well early this morning) of the 6.83 GB / 9.7k files from gov.uk

**Some analysis of the images:**

(pic1)  it takes about 6 minutes to pre-process the files (from hd1 to hd2) - where this server was processing about 1400 files per minute (which is still very slow and not really taking advantage of all the compute available in the server)
![image](https://user-images.githubusercontent.com/79467690/119000763-b0a30b00-b98b-11eb-8612-6c98a44c1dff.png)

(pic1, pic2, pic3, pic4), once files are in hd2, and we press 'start' there is another (even slower) step that takes place before any file is sent to the SDKs. You can see this by the average files processed now being about 700 per minute (which is basically something being changed with the files still in the 'Initial' stage). this process takes about 13 minutes (which you can see finally starting at pic4, 21 minutes after the process started)
![image](https://user-images.githubusercontent.com/79467690/119001031-ea741180-b98b-11eb-8556-62064663382f.png)
![image](https://user-images.githubusercontent.com/79467690/119001089-f65fd380-b98b-11eb-8514-7d90ca720210.png)
![image](https://user-images.githubusercontent.com/79467690/119001154-02e42c00-b98c-11eb-89c7-6c6ffc024476.png)

This run was done against the minio version with 5 hot pods, where I was running 60 t3.xlarge servers and 240 threads
With these servers we where averaging about 400 files per minute, 6.6 files per server per minute, and an average process time of ~13 seconds (we really need to look at the performance indicators of the F2F server, since I think this minio version have much more capacity (for example when running just one server I was able to get about 25 files per minute from one server, with 3 to 7 secs process time, which means that I should be able to get about 1500 files per minute with 60 servers)
pic8 shows that the entire processing (of stage 2) took 2,392 seconds, i.e. 39 minutes
![image](https://user-images.githubusercontent.com/79467690/119001232-15f6fc00-b98c-11eb-8fe5-0fe25142c7b3.png)
![image](https://user-images.githubusercontent.com/79467690/119001290-21e2be00-b98c-11eb-830b-b8dcd3308eff.png)
![image](https://user-images.githubusercontent.com/79467690/119001344-2dce8000-b98c-11eb-8f30-cc46e655eed9.png)
![image](https://user-images.githubusercontent.com/79467690/119001396-39ba4200-b98c-11eb-95a0-3c6d92f06ece.png)

**Comment by MaNe2020** [comment]
20.05. 

![govUk2005](https://user-images.githubusercontent.com/70108899/119155738-c4b23f80-ba53-11eb-8888-eedf6bf7e738.PNG)

**Comment by MaNe2020** [comment]
21.05.

![govUk2105](https://user-images.githubusercontent.com/70108899/119155780-d0056b00-ba53-11eb-89db-7d7d8cd97242.PNG)
![govUk2105threat](https://user-images.githubusercontent.com/70108899/119155787-d1cf2e80-ba53-11eb-8ea0-d698b4c0113d.PNG)
![govUkthreat2105_2](https://user-images.githubusercontent.com/70108899/119155788-d1cf2e80-ba53-11eb-9403-af826eeb9de2.PNG)


HIGH THREAT
![high_threat](https://user-images.githubusercontent.com/70108899/119155842-e1e70e00-ba53-11eb-95ff-d594e126d064.PNG)

**Comment by MaNe2020** [comment]
Using regular GW SDK as minio version has high % of errors.
And runs are run with 100 threads

**Comment by MaNe2020** [comment]
@kekesimarti @GINAGC 
run from today, 31th, 5 GW SDK IPs and 50 threads
![image](https://user-images.githubusercontent.com/70108899/120205512-5414db00-c22a-11eb-93e4-eca20b0c49e7.png)
![image](https://user-images.githubusercontent.com/70108899/120205601-6bec5f00-c22a-11eb-99bb-f75c5b9dca8c.png)

**Comment by MaNe2020** [comment]
Also what do you think about closing this one?
I do not think it is needed anymore.
I will move to contacting ppl from GW about additional information regarding data and if we can improve smth. And will work on analyzing previous runs and results. 
Continuation of this can be done via https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/394
