### ISSUE TITLE
Fixes for Crashed main loop #Bug36

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#408]
Discuss the fixes for[ #Bug 36](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/36):
1. Who reported the bug: Dinis
2. More context of the bug: This happened when there were no valid endpoints
3. Proofs of the bug:
![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/3ff875aa-4682-4085-a63f-8588f3206792)

![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/93f3ac05-6465-4ba6-b4f7-1b78583ec43c)

![image.png](https://images.zenhubusercontent.com/6033d6c0a356dc6005080557/7acb8a33-7549-42cd-aff9-197372fc51af)

**Comment by DinisCruz** [comment]
fixed in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/399

**Comment by MaNe2020** [comment]
The 500 error will not be displayed if no IPs are avl (to be assigned dynamically).
![image](https://user-images.githubusercontent.com/70108899/120187874-ae577100-c215-11eb-83d1-17026f8df161.png)

Created new issue: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/41
that will add message to output folder that there is not IPs avl for processing to start.
