### ISSUE TITLE
split docker-compose

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/cdr-plugin-folder-to-folder#413]
The docker-compose file is starting to be quite big and it will be better to refactor it into separate files

looks like the current best solution is to use the -f switch (https://medium.com/@piotr.macha/how-to-split-your-huge-docker-compose-into-multiple-files-3c8866e495dd) which has the side effect of breaking the main 'docker-compose-up'

I think the extends capability (https://docs.docker.com/compose/extends/) 
![image](https://user-images.githubusercontent.com/656739/119267405-5487f300-bbe6-11eb-8235-a9309a76123e.png) looks much better

this is related to #261

**Comment by GINAGC** [comment]
@DinisCruz what was the PR for this issue?
