### ISSUE TITLE
website fails to build on docker and docker-compose

### ISSUE THREAD

**Issue by DinisCruz** [filetrust/cdr-plugin-folder-to-folder#420]
replicate issue using `docker-compose up` or via `bin/website-docker-build-run.sh`

here is the error 
![image](https://user-images.githubusercontent.com/656739/119270567-32e23800-bbf5-11eb-8bd0-4220ca25ba45.png)

**Comment by GINAGC** [comment]
@rajmbcoderx should this one be moved to QA now? please also add a comment about the fix.
