### ISSUE TITLE
In analysis_json file_name is doubled

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#423]
1. Run f2f workflow
2. Navigate to Elastic
3. Go to Threat analysis Dashboard
4. Go to Discovery

In both 3 and 4, analysis_json data have  file_name

![image](https://user-images.githubusercontent.com/70108899/119310993-d02e8200-bc70-11eb-878f-761f88f3ae7e.png)

**Comment by GINAGC** [comment]
@ggrig can you take a look to this? what part of the process is causing this?

**Comment by ggrig** [comment]
@MaNe2020 @GINAGC 
I do not reproduce the issue locally 
![image](https://user-images.githubusercontent.com/26714598/119461751-0e02d780-bd51-11eb-84df-26d9d76b726c.png)
Would you please specify the environment/test setup where the issue has been revealed

**Comment by GINAGC** [comment]
sending to @MaNe2020 to check and add more info.

**Comment by kekesimarti** [comment]
@GINAGC  Is this version `v0.8.3`?

**Comment by MaNe2020** [comment]
@ggrig I am still seeing this
![image](https://user-images.githubusercontent.com/70108899/119639904-589b5700-be18-11eb-8940-95eb5bcffcdf.png)

This is with latest changes from develop and on govUk dataset.

Please use govUk dataset to check, as on the other one I tried I haven't seen it. 

@GINAGC I don't have any more details to add.

**Comment by ggrig** [comment]
@MaNe2020 
What is the location of govUk dataset?

**Comment by MaNe2020** [comment]
@ggrig just figure it out.
Will close this one. 
Seems like govUK files have names that are doubled. So this is not an issue.
