### ISSUE TITLE
Create a baseline on these steps

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#433]
We need to understand the times on each of these steps:

1. Upload from F2F to Cloud SDK (network bandwidth)
2. Cloud SDK to Minio
3. Minio to Rebuild pod
4. Glasswall engine processing the file (this is where the big variance should happen)
5. Rebuild pod to Minio
6. Mino to CLoud SDK
7. Cloud SDK to F2F

**Comment by MaNe2020** [comment]
@GINAGC @chrisdiao pls check with this one and verify if this should be assigned to someone else.
@samarthdd and @Lestat06 are doing lot of testing so maybe they can provide some info even now.

**Comment by GINAGC** [comment]
we will do this on the automation project
