### ISSUE TITLE
Create UI design for workflows feature that will also caters the issues reported towards usability

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#434]

**Comment by nishantswarup** [comment]
![Uploading Screenshot 2021-05-27 at 4.43.44 PM.png…]()

**Comment by nishant** [comment]
wrong user mentioned fyi.
unsubbing from this thread.

**Comment by chrisdiao** [comment]
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue if there is any.

**Comment by MaNe2020** [comment]
I will close this one as we already started to work on this and new issues are opened accordingly.
