### ISSUE TITLE
Develop Configuration section on the workflows that has set baseDir, threads, cloud Ip

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#435]

**Comment by chrisdiao** [comment]
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue is there is any.

**Comment by nishantswarup** [comment]
Fixed https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment]
Duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/436 
Will close this one.
