### ISSUE TITLE
Develop and integrate APIs for Configuration to set baseDir, threads, cloud Ip

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#436]

**Comment by chrisdiao** [comment]
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue if there is any.

**Comment by nishantswarup** [comment]
Fixed in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment]
Before release to main this needs to be fixed: filetrust/cdr-plugin-folder-to-folder-bugs#62

**Comment by nishantswarup** [comment]
raised the PR 
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/541

**Comment by MaNe2020** [comment]
verified and moving for release

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
