### ISSUE TITLE
Develop UI for Processing[ start, stop, load, clear] section

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#438]

**Comment by chrisdiao** [comment]
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue if there is any.

**Comment by nishantswarup** [comment]
fixed in pr https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment]
This is the duplicate of: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/436
Will close this one. @chrisdiao FYI
