### ISSUE TITLE
Develop and integrate API for start, stop, load, clear

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#439]

**Comment by nishantswarup** [comment]
Fixed in PR https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment]
Before release to main this needs to be fixed: filetrust/cdr-plugin-folder-to-folder-bugs#62

**Comment by nishantswarup** [comment]
raised the PR 
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/541

**Comment by MaNe2020** [comment]
This is done 
![image](https://user-images.githubusercontent.com/70108899/123618314-5dcd3680-d808-11eb-8258-78a4e2a10970.png)
Moving it for release

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
