### ISSUE TITLE
[new UI] Added option to remove IP/PORT, set default port to 80 and fixed few minor UI issues

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#442]

**Comment by MaNe2020** [comment]
![image](https://user-images.githubusercontent.com/70108899/124402721-5e972880-dd32-11eb-84a1-0561ca945341.png)

Changes have been implemented. 
Moving it for Release.

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
