### ISSUE TITLE
Create a Docs page explaining this process

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#444]
1.  Set the minimum instance to be 1 (with the t2.medium)
![image](https://user-images.githubusercontent.com/79467690/119822840-67efd280-bef4-11eb-8a71-c75608acf246.png)

2. which started one instance
![image](https://user-images.githubusercontent.com/79467690/119822967-8b1a8200-bef4-11eb-8eeb-06bc1b82f09c.png)

3.  which has been picked up by the target group
![image](https://user-images.githubusercontent.com/79467690/119823055-ab4a4100-bef4-11eb-823e-ed4296faf782.png)

4. which is configured as a listener in the load balancer
![image](https://user-images.githubusercontent.com/79467690/119823143-c2892e80-bef4-11eb-97a1-f989747f24e3.png)

5.  which is wired up to the dns entry [gw-cloud-sdk-455649808.eu-west-1.elb.amazonaws.com](gw-cloud-sdk-455649808.eu-west-1.elb.amazonaws.com)
![image](https://user-images.githubusercontent.com/79467690/119823275-e51b4780-bef4-11eb-88e3-12d4aef78c1b.png)

**Comment by MaNe2020** [comment]
@kekesimarti I think EAP-docs would be better place for this issue.
Can you pls transfer it to that repo and I will pick up the work from there.

**Comment by kekesimarti** [comment]
@MaNe2020 I moved it [to the EAP Docs repo](https://github.com/k8-proxy/EAP-Docs/issues/13)
