### ISSUE TITLE
Add Pre-Processing integration tests

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#446]
The idea is that every PR that gets merged has to contain the test or instructions on how to test that particular fix.
Spen some time improving some of our test frameworks to allow some of those tests to exist.

**Comment by MaNe2020** [comment]
What is this issue about? What is done to improve this? @chrisdiao

**Comment by chrisdiao** [comment]
@MaNe2020 this task is related to this PR https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/497 and to [this](https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/58) bug

**Comment by MaNe2020** [comment]
@ggrig @chrisdiao I have rename this task, pls check if this is correct.
Moving it for release.

**Comment by chrisdiao** [comment]
This is included in v0.13.0 release
