### ISSUE TITLE
Create an incident playbook

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#448]
Figure out a process and the key questions we need to answer whenever an incident happens.
Create a series of questions and tasks that we want to see hapenning when something happens.
Examples:
What's the architecture?
What's the service set up?
What versions are affected?
What is the version that you run that doesn't have that problem?
What is the exact behaviour that you've seen?
What files are failing?

**Comment by MaNe2020** [comment]
Incident playbook created: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs and shared on channel.
Marti and I had KT with Dharam about the process and can help.

**Comment by GINAGC** [comment]
@kekesimarti we need to add this to the documentation you are mapping. Thanks

**Comment by kekesimarti** [comment]
@GINAGC it's added to the documentation.
