### ISSUE TITLE
x-adaptation-file-id error during file processing

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#454]
1. Navigate to CDR Plugin
2. Set IP to use LB: gw-cloud-sdk-455649808.eu-west-1.elb.amazonaws.com
3. Run any scenario

After step 3, getting 50% of errors due to missing `x-adaptation-file-id`
this is intermittent  issue but it happens from time to time and has huge impact on the processing
![000_err](https://user-images.githubusercontent.com/70108899/120181493-6d5b5e80-c20d-11eb-90e5-c17e58257f53.PNG)

**Comment by MaNe2020** [comment]
@GINAGC @kekesimarti not sure if this is the right board for this issue, so pls move it to corresponding one.
We had this one in past but it seems it appears from time to time and we should have some solution for this.

@samarthdd @dpatel7 FYI

**Comment by MaNe2020** [comment]
Some additional data shared by @samarthdd 
https://glasswall-solutions.slack.com/archives/C01UENXB2DR/p1621932453042200
https://docs.google.com/document/d/1ZHNcudWdNltKRrJFiLDtVpr2Gm5xj2NA-meZVGl-lZU/edit

**Comment by MaNe2020** [comment]
Also tested the same with 5 GW SDKs set directly. Error was not present.
It should be investigated how number of threads from CDR is influencing LB or single IPs. 
And what modifications, wait periods and similar should be added.

**Comment by GINAGC** [comment]
@MaNe2020 do you know the version of the cloud SDK where this was found?

**Comment by GINAGC** [comment]
@samarthdd, @Lestat06 is this still an issue?

**Comment by Lestat06** [comment]
@GINAGC this is still an issue. followed the initial steps from Marija.
Tested with cld-sdk and LB
currently saw it happen only with the LB DNS.

**Comment by samarthdd** [comment]
For this we need to create incident.
We dont have a case to replicate this issue

This is observed in both load balancer  and single IP
According to @dpatel7 this is related to core engine

**Comment by samarthdd** [comment]
incident created : https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/54

**Comment by GINAGC** [comment]
@samarthdd should this one be retested with the latest release?

**Comment by MaNe2020** [comment]
This is still an active issue.
@samarthdd pls provide an update once you have it.
