### ISSUE TITLE
Write Test cases for UI Scenarios for F2F and for Cloud SDK

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#473]

**Comment by MaNe2020** [comment]
@dpatel7 added:

For **cdr-plugin-folder-to-folder** 2 new test sets:
- UI_Tests (12 test cases)
- Functional_Tests (8 test cases)
- Added one new test to Smoke_Tests

For **Cloud SDK** 2 new test sets:
- SDK Functional Tests (6 test cases)
- SDK API Tests (12 test cases)

As project goes we will expend this further. 
Please review and let me know if you would add anything else for this first test sets.

**Comment by MaNe2020** [comment]
Implemented fb from @dpatel7.
We will continue updating test cases regularly. 
Moving this to release column.
