### ISSUE TITLE
For the file being processed, store server, proxy, gateway and file ID headers from GW SDK response into the metadata file

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#474]
@chrisdiao commented on [Tue Jun 08 2021](https://github.com/filetrust/cdr-content-integrity/issues/26)

- x-sdk-api-version
- x-sdk-engine-version
- x-adaptation-file-id
- via
- status Code

**Comment by chrisdiao** [comment]
@MaNe2020 any progress regarding this?

**Comment by MaNe2020** [comment]
Details added in metadata.json
![image](https://user-images.githubusercontent.com/70108899/123615615-c2d35d00-d805-11eb-94e3-c435eac87f7d.png)
Moving it forRelease

**Comment by chrisdiao** [comment]
This is included in v0.13.0 release
