### ISSUE TITLE
add cifs-utils to F2F container

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder#476]
when we build docker image can we add cifs-utils in installation

**Comment by MaNe2020** [comment]
@dpatel7 pls confirm if this is still needed.
@chrisdiao this is small task that if needed can be done by anyone.

**Comment by MaNe2020** [comment]
@chrisdiao This has been added. And CDR can be started without any issues. 
@dpatel7 can you pls add why cifs-utils is needed as per Dinis comment from the daily meeting.

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
