### ISSUE TITLE
Review Snyc detected vulnerabilities for the cdr-plugin-folder-to-folder repo

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#478]
1. Get access to Snyc
2. For the repository assigned, do an analysis of the vulnerabilities detected.
3. Confirm if any of the vulnerabilities can quickly be solved.
4. Confirm from a development perspective which vulnerabilities could have a high impact on the product.
5. Any additional information on the analysis.

**Comment by ggrig** [comment]
Wating for access being approved:

![image](https://user-images.githubusercontent.com/26714598/121347006-ca56c300-c937-11eb-8415-f404f3704c28.png)

**Comment by chrisdiao** [comment]
@ggrig , please confirm if this task could be close already?

**Comment by MaNe2020** [comment]
@ggrig pls check this one and close it if it is done. Or provide other inputs.
