### ISSUE TITLE
Enhance the UI to capture the path for all HD1/HD2 and HD3

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#480]
Enhance the UI to capture the path for all HD1/HD2 and HD3. This will enable easy configuration for any cloud integration that we do.

**Comment by nishantswarup** [comment]
Fixed in this PR 
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/541

**Comment by MaNe2020** [comment]
Done, open the issue: https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/66
for a small UI modification.

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
