### ISSUE TITLE
Broken UI when starting  docker-compose from recent version of the develop branch

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#486]
![image](https://user-images.githubusercontent.com/26714598/121532339-4de3e300-ca10-11eb-8965-12cc605a834b.png)

**Comment by ggrig** [comment]
Steps to reproduce:
- Start EC2 instance from ami-0367280a73f5341de
- Connect to it with  ssh -L 8002:127.0.0.1:5601 -L 8001:127.0.0.1:8888 -L 8003:127.0.0.1:9000 -L 8000:127.0.0.1:8880 8004:127.0.0.1:1313 ubuntu@<instance IP>
- On the ssh terminal run the following:

      cd cdr-plugin-folder-to-folder/
      sudo docker-compose down
      sudo docker stop $(sudo docker ps -aq)
      sudo docker rm $(sudo docker ps -aq)
      sudo docker image rm $(sudo docker images -q)
      git checkout develop
      git pull
      sudo docker-compose up
      
Once all services start, try accessing http://localhost:8004/workflows/f2f-workflows/

**Comment by GINAGC** [comment]
@nishantswarup please review this one.

**Comment by GINAGC** [comment]
@MaNe2020 is this fixed?

**Comment by MaNe2020** [comment]
Similar happened to me and son ha on previous code version.
I would leave it open and if I do not encounter this issue will close it.

**Comment by MaNe2020** [comment]
Closing this one as issue is not present in latest pull from develop.
