### ISSUE TITLE
Updates on docs

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#488]
- please fix broken links here: https://filetrust.github.io/cdr-plugin-folder-to-folder/docs/8.-how-to-start/
- and remove OVAs from here: https://filetrust.github.io/cdr-plugin-folder-to-folder/docs/0.-introduction/ this will cause confusion to the team if they want to deploy, since we are not updating the OVAs mentioned here

**Comment by MaNe2020** [comment]
These changes are done. Doc is updated as per comments.

**Comment by chrisdiao** [comment]
this has been released
