### ISSUE TITLE
Improve test coverage of Configure_Env module (currently it's 73.95%)

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#504]

**Comment by MaNe2020** [comment]
As per coveralls test coverage has been increased.
@ggrig pls add details next time how you are calculating coverage as this is not familiar to me.
![image](https://user-images.githubusercontent.com/70108899/124402867-3e1b9e00-dd33-11eb-8a02-e11b20366f57.png)

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
