### ISSUE TITLE
Rename the docs files using underscore ('_') instead of space (' ')

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#512]
Rename the doc files in this DIR website/content/docs

Reference https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/508#discussion_r652665340

**Comment by MaNe2020** [comment]
Will assign this to myself.

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
