### ISSUE TITLE
Add an functionality in the UI to remove specific IP and PORT

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#544]

**Comment by MaNe2020** [comment]
- Default port changed to 80 and change is reflected on UI also
- Delete button added next to each SDK IP

![image](https://user-images.githubusercontent.com/70108899/124402421-779eda00-dd30-11eb-9a3f-cc7b667b8267.png)

Moving it for Release

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
