### ISSUE TITLE
Pre-processing fails if metadata.json is missing for any file in HD2

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#546]
When doing pre-processing or load files without cleaning the data from HD2 and by any chance if metadata.json for any of the has has been removed or missing, this will cause pre-processing to fail with following error

`
>    def load(self):
>       with open(self.metadata_file_path()) as json_file:
> E       FileNotFoundError: [Errno 2] No such file or directory: '/home/raj-upwork/root/cdr-plugin-folder-to-folder-new/test_data/scenario-1/hd2/todo/b94f6f125c79e3a5ffaa826f584c10d52ada669e6762051b826b55776d05aed2/metadata.json'
`

To reproduce this error easily, you can pre-process/load files for any scenario and then delete metadata.json for any of the file. Once this is done, try to pre-process/load files and it would fail.

**Comment by MaNe2020** [comment]
This is no longer an issue.
Tested on scenario-2 example. Moving it for Release.

**Comment by chrisdiao** [comment]
This has been included in v0.14.0 release
