### ISSUE TITLE
Merge into main for release v0.13.0 (from v0.12.5)

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#552]
- v0.12.1 | [Snyk] Security upgrade python from 3.9.3-alpine3.12 to 3.10.0b1-alpine3.12 [#522](#522)
- v0.12.2 | Pre-process twice - issue 58 [#497](#497)
- v0.12.3 | Updated metadata fields - issue 474 [#481](#481)
- v0.12.4 | Changed default aws ips after new deployment of lambdas [#538](#538)
- v0.12.5 | Workflows UI changes, integrated new APIs, auto populate scenarios [#541](#541)

**Comment by MaNe2020** [comment]
@chrisdiao closing this one as this is already merged to main and we have tested v0.13.0
