### ISSUE TITLE
Fix unit test for updated SDK servers

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#555]
The fix is related to the broken pipeline in creating PR where the checks failed
![image](https://user-images.githubusercontent.com/68153062/123659840-acf58480-d865-11eb-919b-7944d4350112.png)

**Comment by chrisdiao** [comment]
Re-run the checks in this [PR](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/553) and verified that all checks executed successfully

![image](https://user-images.githubusercontent.com/68153062/123665910-4bd0af80-d86b-11eb-99c1-18a964a7b4d3.png)

**Comment by MaNe2020** [comment]
@chrisdiao @ggrig I tried reruning the jobs on few PRs but getting this
![image](https://user-images.githubusercontent.com/70108899/123714266-44fb6a00-d876-11eb-835f-57234df8994f.png)
![image](https://user-images.githubusercontent.com/70108899/123714367-74aa7200-d876-11eb-85a3-b770354db8be.png)

**Comment by chrisdiao** [comment]
Hello @ggrig , I also notice the error [here](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/554)

**Comment by chrisdiao** [comment]
@MaNe2020 , could you please confirm this once again? I re-run the failed check in this [PR](https://github.com/filetrust/cdr-content-integrity/pull/59) and it went well

![image](https://user-images.githubusercontent.com/68153062/123786099-e54f9e00-d90b-11eb-82d0-5d3f354984a1.png)

**Comment by chrisdiao** [comment]
@ggrig , could you please provide update on this, please?

**Comment by MaNe2020** [comment]
All recent PRs are passing this. Moving it for Release.

**Comment by chrisdiao** [comment]
This has been included in v0.13.0 release
