### ISSUE TITLE
Update Spira tests 

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#559]
Include new UI changes into current Spira tests

**Comment by MaNe2020** [comment]
This should be done in upcoming week as test should be always up to date with most recent changes.

**Comment by MaNe2020** [comment]
@dpatel7 I have updated CDR test cases:

- API tests, total of 27 test cases added
- UI tests has been changed to be up to date with recent UI changes
- 2 functional tests that were TBD have been updated

Pls review and let me know if any change is needed.

**Comment by dpatel7** [comment]
@MaNe2020 I am happy with update. I am closing the issue
