### ISSUE TITLE
Kubernetes based deployment 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#562]

**Comment by GINAGC** [comment]
@chrisdiao this is one issue that we need to review the priority with Dinis.

**Comment by chrisdiao** [comment]
got it @GINAGC , will have this in my list for our next discussion with Dinis

**Comment by MaNe2020** [comment]
@GINAGC @chrisdiao this is a duplicate of: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/261
