### ISSUE TITLE
F2F should support adding https SDK IP addresses

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#565]
At the moment if SDK IP is configured to use https (https is allowed on AWS but not the http), when setting the IP, it will through the error that IP is not valid.
Once http is enabled for given SDK IP, setting IP will work.
We should make sure to support https as an infosec recommendation.

**Comment by MaNe2020** [comment]
@chrisdiao added this issue to #529 epic.
It should be done as a high priority in order to be in sync with work done on SDK side.
Leaving it as P1.

**Comment by ggrig** [comment]
This has been implemented in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/646

**Comment by chrisdiao** [comment]
Moving this to backlog since this is causing a problem. This has been reverted by [this](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/677) PR.

**Comment by MaNe2020** [comment]
@chrisdiao we have reverted this change I am moving it to in progress.
