### ISSUE TITLE
Root Folder Issue

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#570]
* Need to remove the "scenario-1" in the root_folder entry/value
* Need to rename the root_folder into a better one that makes sense.

![image](https://user-images.githubusercontent.com/68153062/124474922-b33eb000-ddd3-11eb-8463-4697f8e189dc.png)

@MaNe2020 , please add more information if needed.

**Comment by MaNe2020** [comment]
Retested after removing docker image and it works. Will close this one.
