### ISSUE TITLE
Review utilization of functions in file_service.py. Remove unnecessary ones

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#578]
We mainly use https://owasp-sbot.github.io/OSBot-Utils/utils/Files.html for file operations
Review if the utilities in file_service can be replaced with the sbot equivalents
Improve test coverage of file_service.py - currently 68.18%

![image](https://user-images.githubusercontent.com/26714598/124591163-087ad000-de6d-11eb-8932-0d5e4de35e6e.png)

**Comment by MaNe2020** [comment]
As per PR file_service.py has been remove so no coverage is increased for that. 
![image](https://user-images.githubusercontent.com/70108899/126959984-da767f9f-d17f-4547-a149-34309d4c9a0c.png)
Moving for Release
