### ISSUE TITLE
Review utilization of functions in file_utils.py. Remove unnecessary ones

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#582]
We mainly use https://owasp-sbot.github.io/OSBot-Utils/utils/Files.html for file operations
Review if the utilities in file_utils can be replaced with the sbot equivalents
Consider merging necessary ones with file_service.py
Improve test coverage of file_utils.py - currently 68.35%

![image](https://user-images.githubusercontent.com/26714598/124593316-8c35bc00-de6f-11eb-8167-ebfb78c0de0f.png)

**Comment by MaNe2020** [comment]
file_utils.py test coverage is currently at 100%
Moving this for Release
