### ISSUE TITLE
Improve test coverage of Dashboard.py - currently 29.17%

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#583]
Currently, the tests are skipped due to missing elastic connection
Mock objects should be utilized to eliminate the necessity of a running elastic server
![image](https://user-images.githubusercontent.com/26714598/124593822-2695ff80-de70-11eb-83e1-95d378cfd49a.png)

**Comment by MaNe2020** [comment]
@ggrig can you help me to verify this?
From what I see in Coveralls this is increased just by 0.1
![image](https://user-images.githubusercontent.com/70108899/126968359-8e6ed623-078f-4871-a0c2-667ada9cdc08.png)
