### ISSUE TITLE
Improve test coverage of Kibana.py - currently 44.12

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#586]
Currently, the tests are skipped due to missing elastic connection
Mock objects should be utilized to eliminate the necessity of a running elastic server

![image](https://user-images.githubusercontent.com/26714598/124594495-e6834c80-de70-11eb-8f56-e4d1bdafc5e7.png)

**Comment by MaNe2020** [comment]
Moving for release. Kibana.py is on 98.04 now 
![image](https://user-images.githubusercontent.com/70108899/128328009-237dcfe7-96a8-4b02-b992-d2e23b9084a6.png)
