### ISSUE TITLE
Create more detailed data/code flow diagrams

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#59]
create more detailed data/code flow diagrams (i.e. boxes and arrows) using code so that we can zoom in into what is actually going on, and we create the materials for threat models.

**Comment by MaNe2020** [comment]
Additional comments on the task

try implement this by using: https://c4model.com/ based on example from - 
https://github.com/k8-proxy/GW-proxy/pull/63/files
https://github.com/k8-proxy-glacier/k8-traffic-generator/pull/78
