### ISSUE TITLE
Implement an API endpoint to Generate Detail analysis of report.json

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#592]
- This should contain the summary of all processed files
- The endpoint should return a json structure that contains the bellow information

file name | file type | size | remediated item count | remediate items list | sanitised item count | sanitised items list | issue item count | issue item list | content items list | content items count | library version |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

This is the continuation of below task.
Reference: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/139

**Comment by ggrig** [comment]
@dpatel7 
Do we expect the output to be a JSON list of combined Analysis.json reports?
Or is it about a summary report?

**Comment by MaNe2020** [comment]
Endpoint present and working: 
![image](https://user-images.githubusercontent.com/70108899/128332803-6f572c5c-a20f-4b72-ab24-88968eb66d35.png)

Opened an issue for documenting this: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/701

Moving for Release.
