### ISSUE TITLE
Remove Jupyter Notebook in the F2F Plugin Solution

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#595]
And need to update the documentation

**Comment by Girish-pingala** [comment]
@chrisdiao PR #647 has been raised.
@pranaysahith Please validate and merge PR #647

**Comment by MaNe2020** [comment]
@chrisdiao this is not complete work that needs to be done. 
This should be removed from docker-compose also along with few py scrtipt.
Pls decide if we should to merge this half done and continue or to revert until all changes regarding Jupyter are done.

**Comment by chrisdiao** [comment]
@MaNe2020 , if this will not cause any blocker we will still proceed with this changes and just create a new task for the remaining item that needs to be done.

cc: @Girish-pingala
