### ISSUE TITLE
To fix the failing test cases in F2F smoke test pack in GIT hub action

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#597]
To fix the failing test cases in F2F smoke test pack in GIT hub action

Looks like port being used in accessing the UI and Minio are wrong.

Issue URL: https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/2839898396?check_suite_focus=true

Failing scenarios:
features/f2fBase_State.feature:14 User can access Minio -- @1.3 dockerContainers
features/f2fBase_State.feature:15 User can access UI -- @1.4 dockerContainers

Original Task can be found [here](https://github.com/filetrust/cdr-plugin-f2f-automation-tests/issues/42)

**Comment by MaNe2020** [comment]
@chrisdiao there is a lot of information missing here:
- who worked on this
- where is the PR or where to see fix
- how this is to be tested

I tried enabling workflow and re running this but from there this is still not working:
https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/3037816507?check_suite_focus=true

**Comment by chrisdiao** [comment]
@MaNe2020 , [this](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/590) is the PR for this task.

cc: @dpatel7

**Comment by MaNe2020** [comment]
This has been verified.
https://github.com/filetrust/cdr-plugin-folder-to-folder/runs/3054520577?check_suite_focus=true
Moving for Release.

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
