### ISSUE TITLE
F2F training

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#601]
1.- Start by reviewing the project documentation https://filetrust.github.io/cdr-plugin-folder-to-folder/docs/
2.- Understand the concept of original file versus a rebuilt file, you can also play with this online example https://cloud-sdk.glasswallsolutions.com/
3.- Deploy the F2F solution in AWS and raise any questions.

As a deliverable: Please write a list of requirements (a simple list) that you identify for this project as part of the deliverable.

**Comment by aghapygad336** [comment]
Received ,Thanks for informing me .

**Comment by aghapygad336** [comment]
## Deployment Steps to be more easier
Use latest CDR Plugin AMI.

AMI ID can be found in github actions: https://github.com/filetrust/cdr-plugin-folder-to-folder/actions/workflows/cdr-plugin.yml

1-Login to AWS Console <br>
2-Navigate to AWS > AMIs <br>
3- Search for the AMI with specific ID from the first step (make sure you are in correct region frpm AWS ) > Europe (Ireland)eu-west-1


4- From AMIs workspace click on specific AMI > Choose Launch
Set instance type to t3.2x.large and extend storage to at least 50GB (in case you are planning to test large data sets set storage to higher value

5-For Instance Tags 
 
        Owner	Aghapy
        Delete	No
        Name	cdr-plugin-1.0V
        Team	Cdr-Plugin
        Scope	Testing
        





Then SSH  your instance VM IP you Can Get from Plugin 



    ssh -L 8002:127.0.0.1:5601 -L 8001:127.0.0.1:8888 -L 8003:127.0.0.1:9000 -L 8000:127.0.0.1:8880 -L 8004:127.0.0.1:1313 -L 8005:127.0.0.1:8866 ubuntu@<VM IP>


![image](https://user-images.githubusercontent.com/46167070/125922223-44590f83-cc80-4f50-bb51-6b8ad12d5324.png)


    

 Then You Got A Happy Access ! 

![image](https://user-images.githubusercontent.com/46167070/125923103-4ac3e20f-31ae-4054-8d07-84856aed5534.png)
    
    

    
    
    
From browser you can now access:

        Minio: localhost:8003
        Jupyter: localhost:8001
        Elastic: localhost:8002
        Swagger: localhost:8000/docs
        Hugo: localhost:8004
        Main UI to use is: localhost:8004


## What's New Here 

1-What's plugin <br>

Plugin has the capabilities to take your DevOps environment to the next level and make it far more productive. <br>
Plugins are created by third-party developers. Most of them keep improving their plugins by adding new features, improving code quality, and keeping them secure. These changes are then released as updates.<br>



2-why we check updates of Plugins <br>
every time Plugin is updated VM_IP changed if IP changed it won't be able to SSH <br>

![image](https://user-images.githubusercontent.com/46167070/125964169-a0e5b5b8-7b83-46a1-8757-e07fae787af2.png)
<br>

3-Building File
Success of rebuild does not depend on hash. It just meant that Glasswall Rebuild Engine picked up the file and that is was able to remove all undesirable content from it.

**Comment by aghapygad336** [comment]
# Test Work Flow 

## 1-Create Scenario
 After Login on our Machine Create the Scenario  and th 3 Hard-disks for testing our Zip File
     
   ![image](https://user-images.githubusercontent.com/46167070/126073545-3822d1b7-6018-4484-be54-948b4972923f.png)


## 2-From AWS we get our File S3 URL

![image](https://user-images.githubusercontent.com/46167070/126073632-d62235ef-0e95-41c0-8f14-0dfb574c5a1c.png)

## 3-Redirect our Scenario 
For me  : Test-QA
![image](https://user-images.githubusercontent.com/46167070/126073935-8ead7a24-8a72-43aa-ba1c-aeb9d188ed95.png)

   ## Post the S3 to our Scenario 
   
![image](https://user-images.githubusercontent.com/46167070/126075357-7cc832ca-99ec-4e3c-a7a5-8de38889c26d.png)

then you check hd1 
![image](https://user-images.githubusercontent.com/46167070/126074306-98dfa652-7102-4ecf-9a86-4bced9a8a4cc.png)



# Got A problem 

All Zip files are n't rebailed

![image](https://user-images.githubusercontent.com/46167070/126083490-b23d1185-7315-4a5c-837a-6cb157c4f5f1.png)

I Tried to launch this instance with the Same (ami-054ab221db1f11ae7 ) Tags And policies but not working Ownered by jurgen

instance ID : i-0be40af323293fe1d

**Comment by aghapygad336** [comment]
## Task is Done 

![image](https://user-images.githubusercontent.com/46167070/126122221-466d4b9c-857e-4816-8e27-ab7b2fca493b.png)

Machine Lunched Succssfuly with SSH 

ssh -L 8002:127.0.0.1:5601 -L 8001:127.0.0.1:8888 -L 8003:127.0.0.1:9000 -L 8004:127.0.0.1:1313 -L 8005:127.0.0.1:8866 -L 8000:127.0.0.1:8880 -i <ur pem key> ubuntu@<ur vm ip>
