### ISSUE TITLE
Develop an endpoint where user can process a files and get the analysis report back

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#603]

**Comment by MaNe2020** [comment]
This is the duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/592 will close it. @chrisdiao

**Comment by MaNe2020** [comment]
Endpoint present and working: 
![image](https://user-images.githubusercontent.com/70108899/128332803-6f572c5c-a20f-4b72-ab24-88968eb66d35.png)

Opened an issue for documenting this: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/701

Moving for Release.
