### ISSUE TITLE
Snyk Infrastructure - Medium findings, affecting Helm, Terraform

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#609]
![image](https://user-images.githubusercontent.com/68153062/125624398-52a15df0-d45b-4b8a-ba9f-abd35f056876.png)

**Comment by Girish-pingala** [comment]
@chrisdiao Please share the snyk URL for above screenshot.

**Comment by GINAGC** [comment]
@Girish-pingala https://app.snyk.io/org/filedrop-cloud-sdk-owt/reports/issues

**Comment by Girish-pingala** [comment]
@chrisdiao @GINAGC Once the PR merged to develop, we need to ask Infosec team to rescan the repo. Let me know if there is any way for us to rescan the repo.

**Comment by GINAGC** [comment]
@Girish-pingala Yes, we can do that after merging. Can you link the PR to this issue please?

**Comment by Girish-pingala** [comment]
@GINAGC It is already been done, you can see above. PR #633 #634 #635

**Comment by GINAGC** [comment]
Thank you. @chrisdiao these PRs need to be reviewed by another devops. You can ask in channel to @pranaysahith

**Comment by Girish-pingala** [comment]
@GINAGC I have already informed @pranaysahith . Also added him as Reviewer.

**Comment by chrisdiao** [comment]
thank you @Girish-pingala !

**Comment by Girish-pingala** [comment]
@chrisdiao PR https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/644 for snyk issues on terraform.

**Comment by MaNe2020** [comment]
@chrisdiao @GINAGC to verify this we need another scan from infosec team that will show above improvements.

**Comment by chrisdiao** [comment]
Hello @MaNe2020 , already informed the infosec team about this PR. Will let you know once feedback is already there.

**Comment by chrisdiao** [comment]
@MaNe2020 , we had a call with @PEpetra a while ago and confirmed that this is already good. The remaining vulnerability now is related to Jupyter which we can ignore since we have an existing [task](https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/665) to totally remove this from the solution.
![image](https://user-images.githubusercontent.com/68153062/127139172-ba612e63-a648-4474-b89e-bd3e4c5bb29b.png)
