### ISSUE TITLE
Testing CDR plugin

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#61]
Validate end to end workflow (from HD1 to HD3) and repeat tests with multiple scenarios:
-- different HD1s
-- different file types
-- validate responses and errors
-- validate results on HD3
-- validate storage on HD2

**Comment by GINAGC** [comment]
@dpatel7 please review and add more validations that should be considered. Thanks

**Comment by MaNe2020** [comment]
@GINAGC I think we can close this one and move to the one regarding volume/performance
