### ISSUE TITLE
Integration tests for Cloud SDK compatibility

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#616]
Test https://cloud-sdk.glasswallsolutions.com/
Make the SDK host a configurable parameter

**Comment by chrisdiao** [comment]
@ggrig , could you add more information on how our QA will be going to test this task, please.

**Comment by ggrig** [comment]
This has been implemented in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/629

**Comment by chrisdiao** [comment]
Moving this to backlog since this is causing a problem. This has been reverted by [this](https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/677) PR.

**Comment by MaNe2020** [comment]
@chrisdiao this cannot be verified as it is blocked by https sdk ips. Will leave it in review column.

**Comment by ggrig** [comment]
@MaNe2020, the changes have never been merged

**Comment by ggrig** [comment]
Implemented in https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/659

**Comment by MaNe2020** [comment]
Tests have been included. Moving this for Release.
