### ISSUE TITLE
Fix python test failure for release 0.15.0

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#619]
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/605

**Comment by MaNe2020** [comment]
Python test are passing in current PR to main 
![image](https://user-images.githubusercontent.com/70108899/126127312-ba871b3f-7654-435f-8de5-89c69645e452.png)

@ggrig pls add what was the issue so we can now in case it happens again.

**Comment by ggrig** [comment]
@MaNe2020 
The issue was a failing default SDK server 
That has been changed to a working one

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
