### ISSUE TITLE
Fix SonarCloud failures for release 0.15.0

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#620]
https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/605

**Comment by MaNe2020** [comment]
SonarCloud test has pass 
![image](https://user-images.githubusercontent.com/70108899/126127116-ac014bd5-7edc-40b3-a741-21c30cb55373.png)
I suppose it can happen again if just SDK IP was the issue.
@ggrig can you pls add details to what was fixed exactly.

**Comment by ggrig** [comment]
@MaNe2020 
Sonar cloud complaint was about similar code in different files
The code has been refactored so that the similarities were eliminated

**Comment by chrisdiao** [comment]
Included this on v0.15.0 release
