### ISSUE TITLE
Organize (bi)weekly SDK + CDR Plugin teams meeting

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#631]
As per `Troubleshooting server errors while performing load test`  on Monday 19.07
it was clear that there is multiple issues.
As meeting was productive we should organize similar meetings on weekly or biweekly level.

**Comment by dtollaku** [comment]
Meeting invite is sent for every Monday for 10 upcoming weeks.
