### ISSUE TITLE
Update on cloud API endpoints (sync releases between F2F and API)

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#632]
In cloud SDK, we are renaming endpoint api/analyse/rebuild-zip-from-base64 to api/SDK/rebuild-zip-from-base64

See details: https://github.com/k8-proxy/cs-k8s-api/pull/515

We need to sync releases with Cloud SDK and F2F, so when we release, we do not break the integration with F2F.

**Comment by ggrig** [comment]
@GINAGC 
I believe that api/analyse/rebuild-zip-from-base64 is being removed
api/SDK/rebuild-zip-from-base64 has been there for a pretty time
So, we can switch to using the last endpoint on F2F side

**Comment by MaNe2020** [comment]
Endpoint has been updated endpoint "api/analyse/rebuild-zip-from-base64" has been replaced with "api/SDK/rebuild-zip-from-base64"
