### ISSUE TITLE
Failures in v0.16.0 pipeline

### ISSUE THREAD

**Issue by ggrig** [filetrust/cdr-plugin-folder-to-folder#671]

**Comment by MaNe2020** [comment]
Something is still failing 
![image](https://user-images.githubusercontent.com/70108899/127486671-823dff26-b184-4bdb-9c64-d985c52f94b8.png)

@chrisdiao @ggrig pls comment if this is expected and if it falls under this task

**Comment by MaNe2020** [comment]
This is related to gitHub actions. And AMI has been built successfully. Moving for Release.
