### ISSUE TITLE
Fix exposed access token

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#676]
[https://github.com/filetrust/cdr-plugin-folder-to-folder/commit/488e07e8f77d6563cb21c2b4377ecda9f6dc1f20](https://github.com/filetrust/cdr-plugin-folder-to-folder/commit/488e07e8f77d6563cb21c2b4377ecda9f6dc1f20)

**Comment by ggrig** [comment]
@kekesimarti 
Where this has been found?
It is the one in a none functional file .env.sample?

**Comment by kekesimarti** [comment]
@ggrig Yes, this was found in .env.sample
This needs to be removed:
![image](https://user-images.githubusercontent.com/79467690/127464170-3af5793a-37d9-48aa-b005-e83f5ac4f429.png)

**Comment by MaNe2020** [comment]
This is not present is .env.sample any more.
@chrisdiao this change should be reflected in docs. 
Moving for Release.
