### ISSUE TITLE
Making separate modules for all three types of VMs in terraform deployment

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-folder-to-folder#70]
- Module - OfflineDesktop - https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/ova/OfflineDesktop.ova
It will be 1 VM need to deploy using this image
 - Modue - GW-SDK - https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/ova/centos-offline-csapi.ova The current code base with number of instances will be required for this VM deployment so customer can choose how many VMs to run using this OVA.
 - Module - WorkflowCluster - https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/cdr-plugin/cdr-plugin-d501b83bbd8ae8456d2f1145b83b94eb7d69b90b-4.ova It will be 1 VM need to deploy using this image

**Comment by spaceport-vlasov-y** [comment]
We have implemented esxi-instance module and used it 3 times for sdk, desktop and workflow instance clusters. https://github.com/filetrust/cdr-plugin-folder-to-folder/blob/main/terraform-ova/main.tf
