### ISSUE TITLE
Diagram to explain the deployment workflow that we have so far with the 3 OVAs 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#73]
Diagram to explain the deployment workflow that we have so far with the 3 OVAs (before we have the automated deployment)

**Comment by MaNe2020** [comment]
![image](https://user-images.githubusercontent.com/70108899/114180791-f9a18180-9940-11eb-8e7a-4f6e5f0528e5.png)

![image](https://user-images.githubusercontent.com/70108899/114180848-12119c00-9941-11eb-8cbe-5a1b4ba544c1.png)
