### ISSUE TITLE
No errors if file is not processed (GW SDK IP is wrong)

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/cdr-plugin-folder-to-folder#98]
Go to Jupyter Notebooks and run Use case 2.
Set GW SDK IP for incorrect value.
File will not be process but no error details will be shown 

![image](https://user-images.githubusercontent.com/70108899/114370981-58087300-9b80-11eb-82bd-6b10e98fed24.png)

**Comment by samarthdd** [comment]
@MaNe2020 @GINAGC this is fixed

if gw sdk is not working, jupyter will throw error

If file is not processed by gw sdk for some reason, it will be updated in events.json aswell as elastic logs

**Comment by GINAGC** [comment]
@MaNe2020 once that you validate if this is fixed, please close.

**Comment by MaNe2020** [comment]
This one is fixed.
